//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.05.19 at 09:57:17 AM ICT 
//


package sf.sfis.miniesb.esb.realtimeoutbound;

import jakarta.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the sf.sfis.miniesb.esb.realtimeoutbound package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: sf.sfis.miniesb.esb.realtimeoutbound
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link sf.sfis.miniesb.esb.realtimeoutbound.MSG }
     * 
     */
    public sf.sfis.miniesb.esb.realtimeoutbound.MSG createMSG() {
        return new sf.sfis.miniesb.esb.realtimeoutbound.MSG();
    }

    /**
     * Create an instance of {@link RealTimeMessageOUT }
     * 
     */
    public RealTimeMessageOUT createRealTimeMessageOUT() {
        return new RealTimeMessageOUT();
    }

    /**
     * Create an instance of {@link RealTimeMessageOUT.MSG }
     * 
     */
    public RealTimeMessageOUT.MSG createRealTimeMessageOUTMSG() {
        return new RealTimeMessageOUT.MSG();
    }

    /**
     * Create an instance of {@link RealTimeMessageOUT.MSG.MSGSTREAMOUT }
     * 
     */
    public RealTimeMessageOUT.MSG.MSGSTREAMOUT createRealTimeMessageOUTMSGMSGSTREAMOUT() {
        return new RealTimeMessageOUT.MSG.MSGSTREAMOUT();
    }

    /**
     * Create an instance of {@link RealTimeMessageOUT.MSG.MSGSTREAMOUT.BULKDATA }
     * 
     */
    public RealTimeMessageOUT.MSG.MSGSTREAMOUT.BULKDATA createRealTimeMessageOUTMSGMSGSTREAMOUTBULKDATA() {
        return new RealTimeMessageOUT.MSG.MSGSTREAMOUT.BULKDATA();
    }

    /**
     * Create an instance of {@link RealTimeMessageOUT.MSG.MSGSTREAMOUT.CONCAT }
     * 
     */
    public RealTimeMessageOUT.MSG.MSGSTREAMOUT.CONCAT createRealTimeMessageOUTMSGMSGSTREAMOUTCONCAT() {
        return new RealTimeMessageOUT.MSG.MSGSTREAMOUT.CONCAT();
    }

    /**
     * Create an instance of {@link RealTimeMessageOUT.MSG.MSGSTREAMOUT.STATIC }
     * 
     */
    public RealTimeMessageOUT.MSG.MSGSTREAMOUT.STATIC createRealTimeMessageOUTMSGMSGSTREAMOUTSTATIC() {
        return new RealTimeMessageOUT.MSG.MSGSTREAMOUT.STATIC();
    }

    /**
     * Create an instance of {@link RealTimeMessageOUT.MSG.MSGSTREAMOUT.STATIC.RESOURCES }
     * 
     */
    public RealTimeMessageOUT.MSG.MSGSTREAMOUT.STATIC.RESOURCES createRealTimeMessageOUTMSGMSGSTREAMOUTSTATICRESOURCES() {
        return new RealTimeMessageOUT.MSG.MSGSTREAMOUT.STATIC.RESOURCES();
    }

    /**
     * Create an instance of {@link RealTimeMessageOUT.MSG.MSGSTREAMOUT.STATIC.RESOURCES.COUNTERS }
     * 
     */
    public RealTimeMessageOUT.MSG.MSGSTREAMOUT.STATIC.RESOURCES.COUNTERS createRealTimeMessageOUTMSGMSGSTREAMOUTSTATICRESOURCESCOUNTERS() {
        return new RealTimeMessageOUT.MSG.MSGSTREAMOUT.STATIC.RESOURCES.COUNTERS();
    }

    /**
     * Create an instance of {@link RealTimeMessageOUT.MSG.MSGSTREAMOUT.STATIC.RESOURCES.GATE }
     * 
     */
    public RealTimeMessageOUT.MSG.MSGSTREAMOUT.STATIC.RESOURCES.GATE createRealTimeMessageOUTMSGMSGSTREAMOUTSTATICRESOURCESGATE() {
        return new RealTimeMessageOUT.MSG.MSGSTREAMOUT.STATIC.RESOURCES.GATE();
    }

    /**
     * Create an instance of {@link RealTimeMessageOUT.MSG.MSGSTREAMOUT.STATIC.RESOURCES.BELTS }
     * 
     */
    public RealTimeMessageOUT.MSG.MSGSTREAMOUT.STATIC.RESOURCES.BELTS createRealTimeMessageOUTMSGMSGSTREAMOUTSTATICRESOURCESBELTS() {
        return new RealTimeMessageOUT.MSG.MSGSTREAMOUT.STATIC.RESOURCES.BELTS();
    }

    /**
     * Create an instance of {@link RealTimeMessageOUT.MSG.MSGSTREAMOUT.STATIC.RESOURCES.ACPOSITIONS }
     * 
     */
    public RealTimeMessageOUT.MSG.MSGSTREAMOUT.STATIC.RESOURCES.ACPOSITIONS createRealTimeMessageOUTMSGMSGSTREAMOUTSTATICRESOURCESACPOSITIONS() {
        return new RealTimeMessageOUT.MSG.MSGSTREAMOUT.STATIC.RESOURCES.ACPOSITIONS();
    }

    /**
     * Create an instance of {@link RealTimeMessageOUT.MSG.MSGSTREAMOUT.INFOBJVDGS }
     * 
     */
    public RealTimeMessageOUT.MSG.MSGSTREAMOUT.INFOBJVDGS createRealTimeMessageOUTMSGMSGSTREAMOUTINFOBJVDGS() {
        return new RealTimeMessageOUT.MSG.MSGSTREAMOUT.INFOBJVDGS();
    }

    /**
     * Create an instance of {@link RealTimeMessageOUT.MSG.MSGSTREAMOUT.INFOBJGATE }
     * 
     */
    public RealTimeMessageOUT.MSG.MSGSTREAMOUT.INFOBJGATE createRealTimeMessageOUTMSGMSGSTREAMOUTINFOBJGATE() {
        return new RealTimeMessageOUT.MSG.MSGSTREAMOUT.INFOBJGATE();
    }

    /**
     * Create an instance of {@link RealTimeMessageOUT.MSG.MSGSTREAMOUT.INFOBJACPOSITION }
     * 
     */
    public RealTimeMessageOUT.MSG.MSGSTREAMOUT.INFOBJACPOSITION createRealTimeMessageOUTMSGMSGSTREAMOUTINFOBJACPOSITION() {
        return new RealTimeMessageOUT.MSG.MSGSTREAMOUT.INFOBJACPOSITION();
    }

    /**
     * Create an instance of {@link com.example.generated.MSG.MSGSTREAMOUT }
     * 
     */
    public sf.sfis.miniesb.esb.realtimeoutbound.MSG.MSGSTREAMOUT createMSGMSGSTREAMOUT() {
        return new sf.sfis.miniesb.esb.realtimeoutbound.MSG.MSGSTREAMOUT();
    }

    /**
     * Create an instance of {@link com.example.generated.MSG.MSGSTREAMOUT.BULKDATA }
     * 
     */
    public sf.sfis.miniesb.esb.realtimeoutbound.MSG.MSGSTREAMOUT.BULKDATA createMSGMSGSTREAMOUTBULKDATA() {
        return new sf.sfis.miniesb.esb.realtimeoutbound.MSG.MSGSTREAMOUT.BULKDATA();
    }

    /**
     * Create an instance of {@link com.example.generated.MSG.MSGSTREAMOUT.CONCAT }
     * 
     */
    public sf.sfis.miniesb.esb.realtimeoutbound.MSG.MSGSTREAMOUT.CONCAT createMSGMSGSTREAMOUTCONCAT() {
        return new sf.sfis.miniesb.esb.realtimeoutbound.MSG.MSGSTREAMOUT.CONCAT();
    }

    /**
     * Create an instance of {@link com.example.generated.MSG.MSGSTREAMOUT.STATIC }
     * 
     */
    public sf.sfis.miniesb.esb.realtimeoutbound.MSG.MSGSTREAMOUT.STATIC createMSGMSGSTREAMOUTSTATIC() {
        return new sf.sfis.miniesb.esb.realtimeoutbound.MSG.MSGSTREAMOUT.STATIC();
    }

    /**
     * Create an instance of {@link sf.sfis.miniesb.esb.realtimeoutbound.MSG.MSGSTREAMOUT.STATIC.RESOURCES }
     * 
     */
    public sf.sfis.miniesb.esb.realtimeoutbound.MSG.MSGSTREAMOUT.STATIC.RESOURCES createMSGMSGSTREAMOUTSTATICRESOURCES() {
        return new sf.sfis.miniesb.esb.realtimeoutbound.MSG.MSGSTREAMOUT.STATIC.RESOURCES();
    }

    /**
     * Create an instance of {@link sf.sfis.miniesb.esb.realtimeoutbound.MSG.MSGSTREAMOUT.STATIC.RESOURCES.COUNTERS }
     * 
     */
    public sf.sfis.miniesb.esb.realtimeoutbound.MSG.MSGSTREAMOUT.STATIC.RESOURCES.COUNTERS createMSGMSGSTREAMOUTSTATICRESOURCESCOUNTERS() {
        return new sf.sfis.miniesb.esb.realtimeoutbound.MSG.MSGSTREAMOUT.STATIC.RESOURCES.COUNTERS();
    }

    /**
     * Create an instance of {@link sf.sfis.miniesb.esb.realtimeoutbound.MSG.MSGSTREAMOUT.STATIC.RESOURCES.GATE }
     * 
     */
    public sf.sfis.miniesb.esb.realtimeoutbound.MSG.MSGSTREAMOUT.STATIC.RESOURCES.GATE createMSGMSGSTREAMOUTSTATICRESOURCESGATE() {
        return new sf.sfis.miniesb.esb.realtimeoutbound.MSG.MSGSTREAMOUT.STATIC.RESOURCES.GATE();
    }

    /**
     * Create an instance of {@link sf.sfis.miniesb.esb.realtimeoutbound.MSG.MSGSTREAMOUT.STATIC.RESOURCES.BELTS }
     * 
     */
    public sf.sfis.miniesb.esb.realtimeoutbound.MSG.MSGSTREAMOUT.STATIC.RESOURCES.BELTS createMSGMSGSTREAMOUTSTATICRESOURCESBELTS() {
        return new sf.sfis.miniesb.esb.realtimeoutbound.MSG.MSGSTREAMOUT.STATIC.RESOURCES.BELTS();
    }

    /**
     * Create an instance of {@link sf.sfis.miniesb.esb.realtimeoutbound.MSG.MSGSTREAMOUT.STATIC.RESOURCES.ACPOSITIONS }
     * 
     */
    public sf.sfis.miniesb.esb.realtimeoutbound.MSG.MSGSTREAMOUT.STATIC.RESOURCES.ACPOSITIONS createMSGMSGSTREAMOUTSTATICRESOURCESACPOSITIONS() {
        return new sf.sfis.miniesb.esb.realtimeoutbound.MSG.MSGSTREAMOUT.STATIC.RESOURCES.ACPOSITIONS();
    }

    /**
     * Create an instance of {@link sf.sfis.miniesb.esb.realtimeoutbound.MSG.MSGSTREAMOUT.INFOBJVDGS }
     * 
     */
    public sf.sfis.miniesb.esb.realtimeoutbound.MSG.MSGSTREAMOUT.INFOBJVDGS createMSGMSGSTREAMOUTINFOBJVDGS() {
        return new sf.sfis.miniesb.esb.realtimeoutbound.MSG.MSGSTREAMOUT.INFOBJVDGS();
    }

    /**
     * Create an instance of {@link sf.sfis.miniesb.esb.realtimeoutbound.MSG.MSGSTREAMOUT.INFOBJGATE }
     * 
     */
    public sf.sfis.miniesb.esb.realtimeoutbound.MSG.MSGSTREAMOUT.INFOBJGATE createMSGMSGSTREAMOUTINFOBJGATE() {
        return new sf.sfis.miniesb.esb.realtimeoutbound.MSG.MSGSTREAMOUT.INFOBJGATE();
    }

    /**
     * Create an instance of {@link sf.sfis.miniesb.esb.realtimeoutbound.MSG.MSGSTREAMOUT.INFOBJACPOSITION }
     * 
     */
    public sf.sfis.miniesb.esb.realtimeoutbound.MSG.MSGSTREAMOUT.INFOBJACPOSITION createMSGMSGSTREAMOUTINFOBJACPOSITION() {
        return new sf.sfis.miniesb.esb.realtimeoutbound.MSG.MSGSTREAMOUT.INFOBJACPOSITION();
    }

    /**
     * Create an instance of {@link RealTimeMessageOUT.MSG.MSGSTREAMOUT.INFOBJGENERIC }
     * 
     */
    public RealTimeMessageOUT.MSG.MSGSTREAMOUT.INFOBJGENERIC createRealTimeMessageOUTMSGMSGSTREAMOUTINFOBJGENERIC() {
        return new RealTimeMessageOUT.MSG.MSGSTREAMOUT.INFOBJGENERIC();
    }

    /**
     * Create an instance of {@link RealTimeMessageOUT.MSG.MSGSTREAMOUT.INFOBJFLIGHT }
     * 
     */
    public RealTimeMessageOUT.MSG.MSGSTREAMOUT.INFOBJFLIGHT createRealTimeMessageOUTMSGMSGSTREAMOUTINFOBJFLIGHT() {
        return new RealTimeMessageOUT.MSG.MSGSTREAMOUT.INFOBJFLIGHT();
    }

    /**
     * Create an instance of {@link RealTimeMessageOUT.MSG.MSGSTREAMOUT.INFOBJBELT }
     * 
     */
    public RealTimeMessageOUT.MSG.MSGSTREAMOUT.INFOBJBELT createRealTimeMessageOUTMSGMSGSTREAMOUTINFOBJBELT() {
        return new RealTimeMessageOUT.MSG.MSGSTREAMOUT.INFOBJBELT();
    }

    /**
     * Create an instance of {@link RealTimeMessageOUT.MSG.MSGSTREAMOUT.INFOBJCOUNTER }
     * 
     */
    public RealTimeMessageOUT.MSG.MSGSTREAMOUT.INFOBJCOUNTER createRealTimeMessageOUTMSGMSGSTREAMOUTINFOBJCOUNTER() {
        return new RealTimeMessageOUT.MSG.MSGSTREAMOUT.INFOBJCOUNTER();
    }

    /**
     * Create an instance of {@link RealTimeMessageOUT.MSG.MSGSTREAMOUT.INFOBJLOUNGE }
     * 
     */
    public RealTimeMessageOUT.MSG.MSGSTREAMOUT.INFOBJLOUNGE createRealTimeMessageOUTMSGMSGSTREAMOUTINFOBJLOUNGE() {
        return new RealTimeMessageOUT.MSG.MSGSTREAMOUT.INFOBJLOUNGE();
    }

    /**
     * Create an instance of {@link RealTimeMessageOUT.MSG.MSGSTREAMOUT.INFOBJEXIT }
     * 
     */
    public RealTimeMessageOUT.MSG.MSGSTREAMOUT.INFOBJEXIT createRealTimeMessageOUTMSGMSGSTREAMOUTINFOBJEXIT() {
        return new RealTimeMessageOUT.MSG.MSGSTREAMOUT.INFOBJEXIT();
    }

    /**
     * Create an instance of {@link RealTimeMessageOUT.MSG.MSGSTREAMOUT.BULKDATA.METAR }
     * 
     */
    public RealTimeMessageOUT.MSG.MSGSTREAMOUT.BULKDATA.METAR createRealTimeMessageOUTMSGMSGSTREAMOUTBULKDATAMETAR() {
        return new RealTimeMessageOUT.MSG.MSGSTREAMOUT.BULKDATA.METAR();
    }

    /**
     * Create an instance of {@link RealTimeMessageOUT.MSG.MSGSTREAMOUT.BULKDATA.SITA }
     * 
     */
    public RealTimeMessageOUT.MSG.MSGSTREAMOUT.BULKDATA.SITA createRealTimeMessageOUTMSGMSGSTREAMOUTBULKDATASITA() {
        return new RealTimeMessageOUT.MSG.MSGSTREAMOUT.BULKDATA.SITA();
    }

    /**
     * Create an instance of {@link RealTimeMessageOUT.MSG.MSGSTREAMOUT.BULKDATA.AFTN }
     * 
     */
    public RealTimeMessageOUT.MSG.MSGSTREAMOUT.BULKDATA.AFTN createRealTimeMessageOUTMSGMSGSTREAMOUTBULKDATAAFTN() {
        return new RealTimeMessageOUT.MSG.MSGSTREAMOUT.BULKDATA.AFTN();
    }

    /**
     * Create an instance of {@link RealTimeMessageOUT.MSG.MSGSTREAMOUT.CONCAT.TOWINGS }
     * 
     */
    public RealTimeMessageOUT.MSG.MSGSTREAMOUT.CONCAT.TOWINGS createRealTimeMessageOUTMSGMSGSTREAMOUTCONCATTOWINGS() {
        return new RealTimeMessageOUT.MSG.MSGSTREAMOUT.CONCAT.TOWINGS();
    }

    /**
     * Create an instance of {@link RealTimeMessageOUT.MSG.MSGSTREAMOUT.STATIC.RESOURCES.COMMONCOUNTERS }
     * 
     */
    public RealTimeMessageOUT.MSG.MSGSTREAMOUT.STATIC.RESOURCES.COMMONCOUNTERS createRealTimeMessageOUTMSGMSGSTREAMOUTSTATICRESOURCESCOMMONCOUNTERS() {
        return new RealTimeMessageOUT.MSG.MSGSTREAMOUT.STATIC.RESOURCES.COMMONCOUNTERS();
    }

    /**
     * Create an instance of {@link RealTimeMessageOUT.MSG.MSGSTREAMOUT.STATIC.RESOURCES.COUNTERS.STATICCOUNTER }
     * 
     */
    public RealTimeMessageOUT.MSG.MSGSTREAMOUT.STATIC.RESOURCES.COUNTERS.STATICCOUNTER createRealTimeMessageOUTMSGMSGSTREAMOUTSTATICRESOURCESCOUNTERSSTATICCOUNTER() {
        return new RealTimeMessageOUT.MSG.MSGSTREAMOUT.STATIC.RESOURCES.COUNTERS.STATICCOUNTER();
    }

    /**
     * Create an instance of {@link RealTimeMessageOUT.MSG.MSGSTREAMOUT.STATIC.RESOURCES.GATE.STATICGATE }
     * 
     */
    public RealTimeMessageOUT.MSG.MSGSTREAMOUT.STATIC.RESOURCES.GATE.STATICGATE createRealTimeMessageOUTMSGMSGSTREAMOUTSTATICRESOURCESGATESTATICGATE() {
        return new RealTimeMessageOUT.MSG.MSGSTREAMOUT.STATIC.RESOURCES.GATE.STATICGATE();
    }

    /**
     * Create an instance of {@link RealTimeMessageOUT.MSG.MSGSTREAMOUT.STATIC.RESOURCES.BELTS.STATICBELT }
     * 
     */
    public RealTimeMessageOUT.MSG.MSGSTREAMOUT.STATIC.RESOURCES.BELTS.STATICBELT createRealTimeMessageOUTMSGMSGSTREAMOUTSTATICRESOURCESBELTSSTATICBELT() {
        return new RealTimeMessageOUT.MSG.MSGSTREAMOUT.STATIC.RESOURCES.BELTS.STATICBELT();
    }

    /**
     * Create an instance of {@link RealTimeMessageOUT.MSG.MSGSTREAMOUT.STATIC.RESOURCES.ACPOSITIONS.STATICACPOSITION }
     * 
     */
    public RealTimeMessageOUT.MSG.MSGSTREAMOUT.STATIC.RESOURCES.ACPOSITIONS.STATICACPOSITION createRealTimeMessageOUTMSGMSGSTREAMOUTSTATICRESOURCESACPOSITIONSSTATICACPOSITION() {
        return new RealTimeMessageOUT.MSG.MSGSTREAMOUT.STATIC.RESOURCES.ACPOSITIONS.STATICACPOSITION();
    }

    /**
     * Create an instance of {@link RealTimeMessageOUT.MSG.MSGSTREAMOUT.INFOBJVDGS.VDGSARR }
     * 
     */
    public RealTimeMessageOUT.MSG.MSGSTREAMOUT.INFOBJVDGS.VDGSARR createRealTimeMessageOUTMSGMSGSTREAMOUTINFOBJVDGSVDGSARR() {
        return new RealTimeMessageOUT.MSG.MSGSTREAMOUT.INFOBJVDGS.VDGSARR();
    }

    /**
     * Create an instance of {@link RealTimeMessageOUT.MSG.MSGSTREAMOUT.INFOBJVDGS.VDGSDEP }
     * 
     */
    public RealTimeMessageOUT.MSG.MSGSTREAMOUT.INFOBJVDGS.VDGSDEP createRealTimeMessageOUTMSGMSGSTREAMOUTINFOBJVDGSVDGSDEP() {
        return new RealTimeMessageOUT.MSG.MSGSTREAMOUT.INFOBJVDGS.VDGSDEP();
    }

    /**
     * Create an instance of {@link RealTimeMessageOUT.MSG.MSGSTREAMOUT.INFOBJGATE.GATEARR }
     * 
     */
    public RealTimeMessageOUT.MSG.MSGSTREAMOUT.INFOBJGATE.GATEARR createRealTimeMessageOUTMSGMSGSTREAMOUTINFOBJGATEGATEARR() {
        return new RealTimeMessageOUT.MSG.MSGSTREAMOUT.INFOBJGATE.GATEARR();
    }

    /**
     * Create an instance of {@link RealTimeMessageOUT.MSG.MSGSTREAMOUT.INFOBJGATE.GATEDEP }
     * 
     */
    public RealTimeMessageOUT.MSG.MSGSTREAMOUT.INFOBJGATE.GATEDEP createRealTimeMessageOUTMSGMSGSTREAMOUTINFOBJGATEGATEDEP() {
        return new RealTimeMessageOUT.MSG.MSGSTREAMOUT.INFOBJGATE.GATEDEP();
    }

    /**
     * Create an instance of {@link RealTimeMessageOUT.MSG.MSGSTREAMOUT.INFOBJACPOSITION.ACPOSITIONARR }
     * 
     */
    public RealTimeMessageOUT.MSG.MSGSTREAMOUT.INFOBJACPOSITION.ACPOSITIONARR createRealTimeMessageOUTMSGMSGSTREAMOUTINFOBJACPOSITIONACPOSITIONARR() {
        return new RealTimeMessageOUT.MSG.MSGSTREAMOUT.INFOBJACPOSITION.ACPOSITIONARR();
    }

    /**
     * Create an instance of {@link RealTimeMessageOUT.MSG.MSGSTREAMOUT.INFOBJACPOSITION.ACPOSITIONDEP }
     * 
     */
    public RealTimeMessageOUT.MSG.MSGSTREAMOUT.INFOBJACPOSITION.ACPOSITIONDEP createRealTimeMessageOUTMSGMSGSTREAMOUTINFOBJACPOSITIONACPOSITIONDEP() {
        return new RealTimeMessageOUT.MSG.MSGSTREAMOUT.INFOBJACPOSITION.ACPOSITIONDEP();
    }

    /**
     * Create an instance of {@link sf.sfis.miniesb.esb.realtimeoutbound.MSG.MSGSTREAMOUT.INFOBJGENERIC }
     * 
     */
    public sf.sfis.miniesb.esb.realtimeoutbound.MSG.MSGSTREAMOUT.INFOBJGENERIC createMSGMSGSTREAMOUTINFOBJGENERIC() {
        return new sf.sfis.miniesb.esb.realtimeoutbound.MSG.MSGSTREAMOUT.INFOBJGENERIC();
    }

    /**
     * Create an instance of {@link sf.sfis.miniesb.esb.realtimeoutbound.MSG.MSGSTREAMOUT.INFOBJFLIGHT }
     * 
     */
    public sf.sfis.miniesb.esb.realtimeoutbound.MSG.MSGSTREAMOUT.INFOBJFLIGHT createMSGMSGSTREAMOUTINFOBJFLIGHT() {
        return new sf.sfis.miniesb.esb.realtimeoutbound.MSG.MSGSTREAMOUT.INFOBJFLIGHT();
    }

    /**
     * Create an instance of {@link sf.sfis.miniesb.esb.realtimeoutbound.MSG.MSGSTREAMOUT.INFOBJBELT }
     * 
     */
    public sf.sfis.miniesb.esb.realtimeoutbound.MSG.MSGSTREAMOUT.INFOBJBELT createMSGMSGSTREAMOUTINFOBJBELT() {
        return new sf.sfis.miniesb.esb.realtimeoutbound.MSG.MSGSTREAMOUT.INFOBJBELT();
    }

    /**
     * Create an instance of {@link sf.sfis.miniesb.esb.realtimeoutbound.MSG.MSGSTREAMOUT.INFOBJCOUNTER }
     * 
     */
    public sf.sfis.miniesb.esb.realtimeoutbound.MSG.MSGSTREAMOUT.INFOBJCOUNTER createMSGMSGSTREAMOUTINFOBJCOUNTER() {
        return new sf.sfis.miniesb.esb.realtimeoutbound.MSG.MSGSTREAMOUT.INFOBJCOUNTER();
    }

    /**
     * Create an instance of {@link sf.sfis.miniesb.esb.realtimeoutbound.MSG.MSGSTREAMOUT.INFOBJLOUNGE }
     * 
     */
    public sf.sfis.miniesb.esb.realtimeoutbound.MSG.MSGSTREAMOUT.INFOBJLOUNGE createMSGMSGSTREAMOUTINFOBJLOUNGE() {
        return new sf.sfis.miniesb.esb.realtimeoutbound.MSG.MSGSTREAMOUT.INFOBJLOUNGE();
    }

    /**
     * Create an instance of {@link sf.sfis.miniesb.esb.realtimeoutbound.MSG.MSGSTREAMOUT.INFOBJEXIT }
     * 
     */
    public sf.sfis.miniesb.esb.realtimeoutbound.MSG.MSGSTREAMOUT.INFOBJEXIT createMSGMSGSTREAMOUTINFOBJEXIT() {
        return new sf.sfis.miniesb.esb.realtimeoutbound.MSG.MSGSTREAMOUT.INFOBJEXIT();
    }

    /**
     * Create an instance of {@link sf.sfis.miniesb.esb.realtimeoutbound.MSG.MSGSTREAMOUT.BULKDATA.METAR }
     * 
     */
    public sf.sfis.miniesb.esb.realtimeoutbound.MSG.MSGSTREAMOUT.BULKDATA.METAR createMSGMSGSTREAMOUTBULKDATAMETAR() {
        return new sf.sfis.miniesb.esb.realtimeoutbound.MSG.MSGSTREAMOUT.BULKDATA.METAR();
    }

    /**
     * Create an instance of {@link sf.sfis.miniesb.esb.realtimeoutbound.MSG.MSGSTREAMOUT.BULKDATA.SITA }
     * 
     */
    public sf.sfis.miniesb.esb.realtimeoutbound.MSG.MSGSTREAMOUT.BULKDATA.SITA createMSGMSGSTREAMOUTBULKDATASITA() {
        return new sf.sfis.miniesb.esb.realtimeoutbound.MSG.MSGSTREAMOUT.BULKDATA.SITA();
    }

    /**
     * Create an instance of {@link sf.sfis.miniesb.esb.realtimeoutbound.MSG.MSGSTREAMOUT.BULKDATA.AFTN }
     * 
     */
    public sf.sfis.miniesb.esb.realtimeoutbound.MSG.MSGSTREAMOUT.BULKDATA.AFTN createMSGMSGSTREAMOUTBULKDATAAFTN() {
        return new sf.sfis.miniesb.esb.realtimeoutbound.MSG.MSGSTREAMOUT.BULKDATA.AFTN();
    }

    /**
     * Create an instance of {@link sf.sfis.miniesb.esb.realtimeoutbound.MSG.MSGSTREAMOUT.CONCAT.TOWINGS }
     * 
     */
    public sf.sfis.miniesb.esb.realtimeoutbound.MSG.MSGSTREAMOUT.CONCAT.TOWINGS createMSGMSGSTREAMOUTCONCATTOWINGS() {
        return new sf.sfis.miniesb.esb.realtimeoutbound.MSG.MSGSTREAMOUT.CONCAT.TOWINGS();
    }

    /**
     * Create an instance of {@link sf.sfis.miniesb.esb.realtimeoutbound.MSG.MSGSTREAMOUT.STATIC.RESOURCES.COMMONCOUNTERS }
     * 
     */
    public sf.sfis.miniesb.esb.realtimeoutbound.MSG.MSGSTREAMOUT.STATIC.RESOURCES.COMMONCOUNTERS createMSGMSGSTREAMOUTSTATICRESOURCESCOMMONCOUNTERS() {
        return new sf.sfis.miniesb.esb.realtimeoutbound.MSG.MSGSTREAMOUT.STATIC.RESOURCES.COMMONCOUNTERS();
    }

    /**
     * Create an instance of {@link sf.sfis.miniesb.esb.realtimeoutbound.MSG.MSGSTREAMOUT.STATIC.RESOURCES.COUNTERS.STATICCOUNTER }
     * 
     */
    public sf.sfis.miniesb.esb.realtimeoutbound.MSG.MSGSTREAMOUT.STATIC.RESOURCES.COUNTERS.STATICCOUNTER createMSGMSGSTREAMOUTSTATICRESOURCESCOUNTERSSTATICCOUNTER() {
        return new sf.sfis.miniesb.esb.realtimeoutbound.MSG.MSGSTREAMOUT.STATIC.RESOURCES.COUNTERS.STATICCOUNTER();
    }

    /**
     * Create an instance of {@link sf.sfis.miniesb.esb.realtimeoutbound.MSG.MSGSTREAMOUT.STATIC.RESOURCES.GATE.STATICGATE }
     * 
     */
    public sf.sfis.miniesb.esb.realtimeoutbound.MSG.MSGSTREAMOUT.STATIC.RESOURCES.GATE.STATICGATE createMSGMSGSTREAMOUTSTATICRESOURCESGATESTATICGATE() {
        return new sf.sfis.miniesb.esb.realtimeoutbound.MSG.MSGSTREAMOUT.STATIC.RESOURCES.GATE.STATICGATE();
    }

    /**
     * Create an instance of {@link sf.sfis.miniesb.esb.realtimeoutbound.MSG.MSGSTREAMOUT.STATIC.RESOURCES.BELTS.STATICBELT }
     * 
     */
    public sf.sfis.miniesb.esb.realtimeoutbound.MSG.MSGSTREAMOUT.STATIC.RESOURCES.BELTS.STATICBELT createMSGMSGSTREAMOUTSTATICRESOURCESBELTSSTATICBELT() {
        return new sf.sfis.miniesb.esb.realtimeoutbound.MSG.MSGSTREAMOUT.STATIC.RESOURCES.BELTS.STATICBELT();
    }

    /**
     * Create an instance of {@link sf.sfis.miniesb.esb.realtimeoutbound.MSG.MSGSTREAMOUT.STATIC.RESOURCES.ACPOSITIONS.STATICACPOSITION }
     * 
     */
    public sf.sfis.miniesb.esb.realtimeoutbound.MSG.MSGSTREAMOUT.STATIC.RESOURCES.ACPOSITIONS.STATICACPOSITION createMSGMSGSTREAMOUTSTATICRESOURCESACPOSITIONSSTATICACPOSITION() {
        return new sf.sfis.miniesb.esb.realtimeoutbound.MSG.MSGSTREAMOUT.STATIC.RESOURCES.ACPOSITIONS.STATICACPOSITION();
    }

    /**
     * Create an instance of {@link sf.sfis.miniesb.esb.realtimeoutbound.MSG.MSGSTREAMOUT.INFOBJVDGS.VDGSARR }
     * 
     */
    public sf.sfis.miniesb.esb.realtimeoutbound.MSG.MSGSTREAMOUT.INFOBJVDGS.VDGSARR createMSGMSGSTREAMOUTINFOBJVDGSVDGSARR() {
        return new sf.sfis.miniesb.esb.realtimeoutbound.MSG.MSGSTREAMOUT.INFOBJVDGS.VDGSARR();
    }

    /**
     * Create an instance of {@link sf.sfis.miniesb.esb.realtimeoutbound.MSG.MSGSTREAMOUT.INFOBJVDGS.VDGSDEP }
     * 
     */
    public sf.sfis.miniesb.esb.realtimeoutbound.MSG.MSGSTREAMOUT.INFOBJVDGS.VDGSDEP createMSGMSGSTREAMOUTINFOBJVDGSVDGSDEP() {
        return new sf.sfis.miniesb.esb.realtimeoutbound.MSG.MSGSTREAMOUT.INFOBJVDGS.VDGSDEP();
    }

    /**
     * Create an instance of {@link sf.sfis.miniesb.esb.realtimeoutbound.MSG.MSGSTREAMOUT.INFOBJGATE.GATEARR }
     * 
     */
    public sf.sfis.miniesb.esb.realtimeoutbound.MSG.MSGSTREAMOUT.INFOBJGATE.GATEARR createMSGMSGSTREAMOUTINFOBJGATEGATEARR() {
        return new sf.sfis.miniesb.esb.realtimeoutbound.MSG.MSGSTREAMOUT.INFOBJGATE.GATEARR();
    }

    /**
     * Create an instance of {@link sf.sfis.miniesb.esb.realtimeoutbound.MSG.MSGSTREAMOUT.INFOBJGATE.GATEDEP }
     * 
     */
    public sf.sfis.miniesb.esb.realtimeoutbound.MSG.MSGSTREAMOUT.INFOBJGATE.GATEDEP createMSGMSGSTREAMOUTINFOBJGATEGATEDEP() {
        return new sf.sfis.miniesb.esb.realtimeoutbound.MSG.MSGSTREAMOUT.INFOBJGATE.GATEDEP();
    }

    /**
     * Create an instance of {@link sf.sfis.miniesb.esb.realtimeoutbound.MSG.MSGSTREAMOUT.INFOBJACPOSITION.ACPOSITIONARR }
     * 
     */
    public sf.sfis.miniesb.esb.realtimeoutbound.MSG.MSGSTREAMOUT.INFOBJACPOSITION.ACPOSITIONARR createMSGMSGSTREAMOUTINFOBJACPOSITIONACPOSITIONARR() {
        return new sf.sfis.miniesb.esb.realtimeoutbound.MSG.MSGSTREAMOUT.INFOBJACPOSITION.ACPOSITIONARR();
    }

    /**
     * Create an instance of {@link sf.sfis.miniesb.esb.realtimeoutbound.MSG.MSGSTREAMOUT.INFOBJACPOSITION.ACPOSITIONDEP }
     * 
     */
    public sf.sfis.miniesb.esb.realtimeoutbound.MSG.MSGSTREAMOUT.INFOBJACPOSITION.ACPOSITIONDEP createMSGMSGSTREAMOUTINFOBJACPOSITIONACPOSITIONDEP() {
        return new sf.sfis.miniesb.esb.realtimeoutbound.MSG.MSGSTREAMOUT.INFOBJACPOSITION.ACPOSITIONDEP();
    }
}
