//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.05.19 at 01:20:59 PM ICT 
//


package sf.sfis.miniesb.esb.realtimeinbound;

import jakarta.xml.bind.JAXBElement;
import jakarta.xml.bind.annotation.XmlElementDecl;
import jakarta.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the sf.sfis.miniesb.esb.realtimeinbound package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _RealTimeMessageINMSGMSGSTREAMINMSGOBJECTSINFOBJMUINFO_QNAME = new QName("", "INFOBJ_MUINFO");
    private final static QName _RealTimeMessageINMSGMSGSTREAMINMSGOBJECTSINFOBJMANIFEST_QNAME = new QName("", "INFOBJ_MANIFEST");
    private final static QName _RealTimeMessageINMSGMSGSTREAMINMSGOBJECTSINFOBJEQUIPMENT_QNAME = new QName("", "INFOBJ_EQUIPMENT");
    private final static QName _RealTimeMessageINMSGMSGSTREAMINMSGOBJECTSINFOBJMUINFOBAZ1_QNAME = new QName("", "BAZ1");
    private final static QName _RealTimeMessageINMSGMSGSTREAMINMSGOBJECTSINFOBJMUINFOBAZ4_QNAME = new QName("", "BAZ4");
    private final static QName _RealTimeMessageINMSGMSGSTREAMINMSGOBJECTSINFOBJMUINFOBAO1_QNAME = new QName("", "BAO1");
    private final static QName _RealTimeMessageINMSGMSGSTREAMINMSGOBJECTSINFOBJMUINFOBAC1_QNAME = new QName("", "BAC1");
    private final static QName _RealTimeMessageINMSGMSGSTREAMINMSGOBJECTSINFOBJMUINFOBAO4_QNAME = new QName("", "BAO4");
    private final static QName _RealTimeMessageINMSGMSGSTREAMINMSGOBJECTSINFOBJMUINFOBAC4_QNAME = new QName("", "BAC4");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: sf.sfis.miniesb.esb.realtimeinbound
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link sf.sfis.miniesb.esb.realtimeinbound.MSG }
     * 
     */
    public sf.sfis.miniesb.esb.realtimeinbound.MSG createMSG() {
        return new sf.sfis.miniesb.esb.realtimeinbound.MSG();
    }

    /**
     * Create an instance of {@link RealTimeMessageIN }
     * 
     */
    public RealTimeMessageIN createRealTimeMessageIN() {
        return new RealTimeMessageIN();
    }

    /**
     * Create an instance of {@link RealTimeMessageIN.MSG }
     * 
     */
    public RealTimeMessageIN.MSG createRealTimeMessageINMSG() {
        return new RealTimeMessageIN.MSG();
    }

    /**
     * Create an instance of {@link RealTimeMessageIN.MSG.MSGSTREAMIN }
     * 
     */
    public RealTimeMessageIN.MSG.MSGSTREAMIN createRealTimeMessageINMSGMSGSTREAMIN() {
        return new RealTimeMessageIN.MSG.MSGSTREAMIN();
    }

    /**
     * Create an instance of {@link RealTimeMessageIN.MSG.MSGSTREAMIN.MSGOBJECTS }
     * 
     */
    public RealTimeMessageIN.MSG.MSGSTREAMIN.MSGOBJECTS createRealTimeMessageINMSGMSGSTREAMINMSGOBJECTS() {
        return new RealTimeMessageIN.MSG.MSGSTREAMIN.MSGOBJECTS();
    }

    /**
     * Create an instance of {@link RealTimeMessageIN.MSG.MSGSTREAMIN.MSGOBJECTS.INFOBJEQUIPMENT }
     * 
     */
    public RealTimeMessageIN.MSG.MSGSTREAMIN.MSGOBJECTS.INFOBJEQUIPMENT createRealTimeMessageINMSGMSGSTREAMINMSGOBJECTSINFOBJEQUIPMENT() {
        return new RealTimeMessageIN.MSG.MSGSTREAMIN.MSGOBJECTS.INFOBJEQUIPMENT();
    }

    /**
     * Create an instance of {@link RealTimeMessageIN.MSG.MSGSTREAMIN.MSGOBJECTS.INFOBJEQUIPMENT.PLB }
     * 
     */
    public RealTimeMessageIN.MSG.MSGSTREAMIN.MSGOBJECTS.INFOBJEQUIPMENT.PLB createRealTimeMessageINMSGMSGSTREAMINMSGOBJECTSINFOBJEQUIPMENTPLB() {
        return new RealTimeMessageIN.MSG.MSGSTREAMIN.MSGOBJECTS.INFOBJEQUIPMENT.PLB();
    }

    /**
     * Create an instance of {@link RealTimeMessageIN.MSG.MSGSTREAMIN.MSGOBJECTS.INFOBJMANIFEST }
     * 
     */
    public RealTimeMessageIN.MSG.MSGSTREAMIN.MSGOBJECTS.INFOBJMANIFEST createRealTimeMessageINMSGMSGSTREAMINMSGOBJECTSINFOBJMANIFEST() {
        return new RealTimeMessageIN.MSG.MSGSTREAMIN.MSGOBJECTS.INFOBJMANIFEST();
    }

    /**
     * Create an instance of {@link RealTimeMessageIN.MSG.MSGSTREAMIN.MSGOBJECTS.BULKDATA }
     * 
     */
    public RealTimeMessageIN.MSG.MSGSTREAMIN.MSGOBJECTS.BULKDATA createRealTimeMessageINMSGMSGSTREAMINMSGOBJECTSBULKDATA() {
        return new RealTimeMessageIN.MSG.MSGSTREAMIN.MSGOBJECTS.BULKDATA();
    }

    /**
     * Create an instance of {@link RealTimeMessageIN.MSG.MSGSTREAMIN.MSGOBJECTS.CONCAT }
     * 
     */
    public RealTimeMessageIN.MSG.MSGSTREAMIN.MSGOBJECTS.CONCAT createRealTimeMessageINMSGMSGSTREAMINMSGOBJECTSCONCAT() {
        return new RealTimeMessageIN.MSG.MSGSTREAMIN.MSGOBJECTS.CONCAT();
    }

    /**
     * Create an instance of {@link RealTimeMessageIN.MSG.MSGSTREAMIN.MSGOBJECTS.STATIC }
     * 
     */
    public RealTimeMessageIN.MSG.MSGSTREAMIN.MSGOBJECTS.STATIC createRealTimeMessageINMSGMSGSTREAMINMSGOBJECTSSTATIC() {
        return new RealTimeMessageIN.MSG.MSGSTREAMIN.MSGOBJECTS.STATIC();
    }

    /**
     * Create an instance of {@link RealTimeMessageIN.MSG.MSGSTREAMIN.MSGOBJECTS.STATIC.RESOURCES }
     * 
     */
    public RealTimeMessageIN.MSG.MSGSTREAMIN.MSGOBJECTS.STATIC.RESOURCES createRealTimeMessageINMSGMSGSTREAMINMSGOBJECTSSTATICRESOURCES() {
        return new RealTimeMessageIN.MSG.MSGSTREAMIN.MSGOBJECTS.STATIC.RESOURCES();
    }

    /**
     * Create an instance of {@link RealTimeMessageIN.MSG.MSGSTREAMIN.MSGOBJECTS.STATIC.RESOURCES.COUNTERS }
     * 
     */
    public RealTimeMessageIN.MSG.MSGSTREAMIN.MSGOBJECTS.STATIC.RESOURCES.COUNTERS createRealTimeMessageINMSGMSGSTREAMINMSGOBJECTSSTATICRESOURCESCOUNTERS() {
        return new RealTimeMessageIN.MSG.MSGSTREAMIN.MSGOBJECTS.STATIC.RESOURCES.COUNTERS();
    }

    /**
     * Create an instance of {@link RealTimeMessageIN.MSG.MSGSTREAMIN.MSGOBJECTS.STATIC.RESOURCES.GATE }
     * 
     */
    public RealTimeMessageIN.MSG.MSGSTREAMIN.MSGOBJECTS.STATIC.RESOURCES.GATE createRealTimeMessageINMSGMSGSTREAMINMSGOBJECTSSTATICRESOURCESGATE() {
        return new RealTimeMessageIN.MSG.MSGSTREAMIN.MSGOBJECTS.STATIC.RESOURCES.GATE();
    }

    /**
     * Create an instance of {@link RealTimeMessageIN.MSG.MSGSTREAMIN.MSGOBJECTS.STATIC.RESOURCES.BELTS }
     * 
     */
    public RealTimeMessageIN.MSG.MSGSTREAMIN.MSGOBJECTS.STATIC.RESOURCES.BELTS createRealTimeMessageINMSGMSGSTREAMINMSGOBJECTSSTATICRESOURCESBELTS() {
        return new RealTimeMessageIN.MSG.MSGSTREAMIN.MSGOBJECTS.STATIC.RESOURCES.BELTS();
    }

    /**
     * Create an instance of {@link RealTimeMessageIN.MSG.MSGSTREAMIN.MSGOBJECTS.STATIC.RESOURCES.ACPOSITIONS }
     * 
     */
    public RealTimeMessageIN.MSG.MSGSTREAMIN.MSGOBJECTS.STATIC.RESOURCES.ACPOSITIONS createRealTimeMessageINMSGMSGSTREAMINMSGOBJECTSSTATICRESOURCESACPOSITIONS() {
        return new RealTimeMessageIN.MSG.MSGSTREAMIN.MSGOBJECTS.STATIC.RESOURCES.ACPOSITIONS();
    }

    /**
     * Create an instance of {@link RealTimeMessageIN.MSG.MSGSTREAMIN.MSGOBJECTS.INFOBJVDGS }
     * 
     */
    public RealTimeMessageIN.MSG.MSGSTREAMIN.MSGOBJECTS.INFOBJVDGS createRealTimeMessageINMSGMSGSTREAMINMSGOBJECTSINFOBJVDGS() {
        return new RealTimeMessageIN.MSG.MSGSTREAMIN.MSGOBJECTS.INFOBJVDGS();
    }

    /**
     * Create an instance of {@link RealTimeMessageIN.MSG.MSGSTREAMIN.MSGOBJECTS.INFOBJGATE }
     * 
     */
    public RealTimeMessageIN.MSG.MSGSTREAMIN.MSGOBJECTS.INFOBJGATE createRealTimeMessageINMSGMSGSTREAMINMSGOBJECTSINFOBJGATE() {
        return new RealTimeMessageIN.MSG.MSGSTREAMIN.MSGOBJECTS.INFOBJGATE();
    }

    /**
     * Create an instance of {@link RealTimeMessageIN.MSG.MSGSTREAMIN.MSGOBJECTS.INFOBJACPOSITION }
     * 
     */
    public RealTimeMessageIN.MSG.MSGSTREAMIN.MSGOBJECTS.INFOBJACPOSITION createRealTimeMessageINMSGMSGSTREAMINMSGOBJECTSINFOBJACPOSITION() {
        return new RealTimeMessageIN.MSG.MSGSTREAMIN.MSGOBJECTS.INFOBJACPOSITION();
    }

    /**
     * Create an instance of {@link sf.sfis.miniesb.esb.realtimeinbound.MSG.MSGSTREAMIN }
     * 
     */
    public sf.sfis.miniesb.esb.realtimeinbound.MSG.MSGSTREAMIN createMSGMSGSTREAMIN() {
        return new sf.sfis.miniesb.esb.realtimeinbound.MSG.MSGSTREAMIN();
    }

    /**
     * Create an instance of {@link sf.sfis.miniesb.esb.realtimeinbound.MSG.MSGSTREAMIN.MSGOBJECTS }
     * 
     */
    public sf.sfis.miniesb.esb.realtimeinbound.MSG.MSGSTREAMIN.MSGOBJECTS createMSGMSGSTREAMINMSGOBJECTS() {
        return new sf.sfis.miniesb.esb.realtimeinbound.MSG.MSGSTREAMIN.MSGOBJECTS();
    }

    /**
     * Create an instance of {@link sf.sfis.miniesb.esb.realtimeinbound.MSG.MSGSTREAMIN.MSGOBJECTS.INFOBJEQUIPMENT }
     * 
     */
    public sf.sfis.miniesb.esb.realtimeinbound.MSG.MSGSTREAMIN.MSGOBJECTS.INFOBJEQUIPMENT createMSGMSGSTREAMINMSGOBJECTSINFOBJEQUIPMENT() {
        return new sf.sfis.miniesb.esb.realtimeinbound.MSG.MSGSTREAMIN.MSGOBJECTS.INFOBJEQUIPMENT();
    }

    /**
     * Create an instance of {@link sf.sfis.miniesb.esb.realtimeinbound.MSG.MSGSTREAMIN.MSGOBJECTS.INFOBJEQUIPMENT.PLB }
     * 
     */
    public sf.sfis.miniesb.esb.realtimeinbound.MSG.MSGSTREAMIN.MSGOBJECTS.INFOBJEQUIPMENT.PLB createMSGMSGSTREAMINMSGOBJECTSINFOBJEQUIPMENTPLB() {
        return new sf.sfis.miniesb.esb.realtimeinbound.MSG.MSGSTREAMIN.MSGOBJECTS.INFOBJEQUIPMENT.PLB();
    }

    /**
     * Create an instance of {@link sf.sfis.miniesb.esb.realtimeinbound.MSG.MSGSTREAMIN.MSGOBJECTS.INFOBJMANIFEST }
     * 
     */
    public sf.sfis.miniesb.esb.realtimeinbound.MSG.MSGSTREAMIN.MSGOBJECTS.INFOBJMANIFEST createMSGMSGSTREAMINMSGOBJECTSINFOBJMANIFEST() {
        return new sf.sfis.miniesb.esb.realtimeinbound.MSG.MSGSTREAMIN.MSGOBJECTS.INFOBJMANIFEST();
    }

    /**
     * Create an instance of {@link sf.sfis.miniesb.esb.realtimeinbound.MSG.MSGSTREAMIN.MSGOBJECTS.BULKDATA }
     * 
     */
    public sf.sfis.miniesb.esb.realtimeinbound.MSG.MSGSTREAMIN.MSGOBJECTS.BULKDATA createMSGMSGSTREAMINMSGOBJECTSBULKDATA() {
        return new sf.sfis.miniesb.esb.realtimeinbound.MSG.MSGSTREAMIN.MSGOBJECTS.BULKDATA();
    }

    /**
     * Create an instance of {@link sf.sfis.miniesb.esb.realtimeinbound.MSG.MSGSTREAMIN.MSGOBJECTS.CONCAT }
     * 
     */
    public sf.sfis.miniesb.esb.realtimeinbound.MSG.MSGSTREAMIN.MSGOBJECTS.CONCAT createMSGMSGSTREAMINMSGOBJECTSCONCAT() {
        return new sf.sfis.miniesb.esb.realtimeinbound.MSG.MSGSTREAMIN.MSGOBJECTS.CONCAT();
    }

    /**
     * Create an instance of {@link sf.sfis.miniesb.esb.realtimeinbound.MSG.MSGSTREAMIN.MSGOBJECTS.STATIC }
     * 
     */
    public sf.sfis.miniesb.esb.realtimeinbound.MSG.MSGSTREAMIN.MSGOBJECTS.STATIC createMSGMSGSTREAMINMSGOBJECTSSTATIC() {
        return new sf.sfis.miniesb.esb.realtimeinbound.MSG.MSGSTREAMIN.MSGOBJECTS.STATIC();
    }

    /**
     * Create an instance of {@link sf.sfis.miniesb.esb.realtimeinbound.MSG.MSGSTREAMIN.MSGOBJECTS.STATIC.RESOURCES }
     * 
     */
    public sf.sfis.miniesb.esb.realtimeinbound.MSG.MSGSTREAMIN.MSGOBJECTS.STATIC.RESOURCES createMSGMSGSTREAMINMSGOBJECTSSTATICRESOURCES() {
        return new sf.sfis.miniesb.esb.realtimeinbound.MSG.MSGSTREAMIN.MSGOBJECTS.STATIC.RESOURCES();
    }

    /**
     * Create an instance of {@link sf.sfis.miniesb.esb.realtimeinbound.MSG.MSGSTREAMIN.MSGOBJECTS.STATIC.RESOURCES.COUNTERS }
     * 
     */
    public sf.sfis.miniesb.esb.realtimeinbound.MSG.MSGSTREAMIN.MSGOBJECTS.STATIC.RESOURCES.COUNTERS createMSGMSGSTREAMINMSGOBJECTSSTATICRESOURCESCOUNTERS() {
        return new sf.sfis.miniesb.esb.realtimeinbound.MSG.MSGSTREAMIN.MSGOBJECTS.STATIC.RESOURCES.COUNTERS();
    }

    /**
     * Create an instance of {@link sf.sfis.miniesb.esb.realtimeinbound.MSG.MSGSTREAMIN.MSGOBJECTS.STATIC.RESOURCES.GATE }
     * 
     */
    public sf.sfis.miniesb.esb.realtimeinbound.MSG.MSGSTREAMIN.MSGOBJECTS.STATIC.RESOURCES.GATE createMSGMSGSTREAMINMSGOBJECTSSTATICRESOURCESGATE() {
        return new sf.sfis.miniesb.esb.realtimeinbound.MSG.MSGSTREAMIN.MSGOBJECTS.STATIC.RESOURCES.GATE();
    }

    /**
     * Create an instance of {@link sf.sfis.miniesb.esb.realtimeinbound.MSG.MSGSTREAMIN.MSGOBJECTS.STATIC.RESOURCES.BELTS }
     * 
     */
    public sf.sfis.miniesb.esb.realtimeinbound.MSG.MSGSTREAMIN.MSGOBJECTS.STATIC.RESOURCES.BELTS createMSGMSGSTREAMINMSGOBJECTSSTATICRESOURCESBELTS() {
        return new sf.sfis.miniesb.esb.realtimeinbound.MSG.MSGSTREAMIN.MSGOBJECTS.STATIC.RESOURCES.BELTS();
    }

    /**
     * Create an instance of {@link sf.sfis.miniesb.esb.realtimeinbound.MSG.MSGSTREAMIN.MSGOBJECTS.STATIC.RESOURCES.ACPOSITIONS }
     * 
     */
    public sf.sfis.miniesb.esb.realtimeinbound.MSG.MSGSTREAMIN.MSGOBJECTS.STATIC.RESOURCES.ACPOSITIONS createMSGMSGSTREAMINMSGOBJECTSSTATICRESOURCESACPOSITIONS() {
        return new sf.sfis.miniesb.esb.realtimeinbound.MSG.MSGSTREAMIN.MSGOBJECTS.STATIC.RESOURCES.ACPOSITIONS();
    }

    /**
     * Create an instance of {@link sf.sfis.miniesb.esb.realtimeinbound.MSG.MSGSTREAMIN.MSGOBJECTS.INFOBJVDGS }
     * 
     */
    public sf.sfis.miniesb.esb.realtimeinbound.MSG.MSGSTREAMIN.MSGOBJECTS.INFOBJVDGS createMSGMSGSTREAMINMSGOBJECTSINFOBJVDGS() {
        return new sf.sfis.miniesb.esb.realtimeinbound.MSG.MSGSTREAMIN.MSGOBJECTS.INFOBJVDGS();
    }

    /**
     * Create an instance of {@link sf.sfis.miniesb.esb.realtimeinbound.MSG.MSGSTREAMIN.MSGOBJECTS.INFOBJGATE }
     * 
     */
    public sf.sfis.miniesb.esb.realtimeinbound.MSG.MSGSTREAMIN.MSGOBJECTS.INFOBJGATE createMSGMSGSTREAMINMSGOBJECTSINFOBJGATE() {
        return new sf.sfis.miniesb.esb.realtimeinbound.MSG.MSGSTREAMIN.MSGOBJECTS.INFOBJGATE();
    }

    /**
     * Create an instance of {@link sf.sfis.miniesb.esb.realtimeinbound.MSG.MSGSTREAMIN.MSGOBJECTS.INFOBJACPOSITION }
     * 
     */
    public sf.sfis.miniesb.esb.realtimeinbound.MSG.MSGSTREAMIN.MSGOBJECTS.INFOBJACPOSITION createMSGMSGSTREAMINMSGOBJECTSINFOBJACPOSITION() {
        return new sf.sfis.miniesb.esb.realtimeinbound.MSG.MSGSTREAMIN.MSGOBJECTS.INFOBJACPOSITION();
    }

    /**
     * Create an instance of {@link RealTimeMessageIN.MSG.MSGSTREAMIN.INFOBJGENERIC }
     * 
     */
    public RealTimeMessageIN.MSG.MSGSTREAMIN.INFOBJGENERIC createRealTimeMessageINMSGMSGSTREAMININFOBJGENERIC() {
        return new RealTimeMessageIN.MSG.MSGSTREAMIN.INFOBJGENERIC();
    }

    /**
     * Create an instance of {@link RealTimeMessageIN.MSG.MSGSTREAMIN.MSGOBJECTS.INFOBJFLIGHT }
     * 
     */
    public RealTimeMessageIN.MSG.MSGSTREAMIN.MSGOBJECTS.INFOBJFLIGHT createRealTimeMessageINMSGMSGSTREAMINMSGOBJECTSINFOBJFLIGHT() {
        return new RealTimeMessageIN.MSG.MSGSTREAMIN.MSGOBJECTS.INFOBJFLIGHT();
    }

    /**
     * Create an instance of {@link RealTimeMessageIN.MSG.MSGSTREAMIN.MSGOBJECTS.INFOBJBELT }
     * 
     */
    public RealTimeMessageIN.MSG.MSGSTREAMIN.MSGOBJECTS.INFOBJBELT createRealTimeMessageINMSGMSGSTREAMINMSGOBJECTSINFOBJBELT() {
        return new RealTimeMessageIN.MSG.MSGSTREAMIN.MSGOBJECTS.INFOBJBELT();
    }

    /**
     * Create an instance of {@link RealTimeMessageIN.MSG.MSGSTREAMIN.MSGOBJECTS.INFOBJCOUNTER }
     * 
     */
    public RealTimeMessageIN.MSG.MSGSTREAMIN.MSGOBJECTS.INFOBJCOUNTER createRealTimeMessageINMSGMSGSTREAMINMSGOBJECTSINFOBJCOUNTER() {
        return new RealTimeMessageIN.MSG.MSGSTREAMIN.MSGOBJECTS.INFOBJCOUNTER();
    }

    /**
     * Create an instance of {@link RealTimeMessageIN.MSG.MSGSTREAMIN.MSGOBJECTS.INFOBJLOUNGE }
     * 
     */
    public RealTimeMessageIN.MSG.MSGSTREAMIN.MSGOBJECTS.INFOBJLOUNGE createRealTimeMessageINMSGMSGSTREAMINMSGOBJECTSINFOBJLOUNGE() {
        return new RealTimeMessageIN.MSG.MSGSTREAMIN.MSGOBJECTS.INFOBJLOUNGE();
    }

    /**
     * Create an instance of {@link RealTimeMessageIN.MSG.MSGSTREAMIN.MSGOBJECTS.INFOBJEXIT }
     * 
     */
    public RealTimeMessageIN.MSG.MSGSTREAMIN.MSGOBJECTS.INFOBJEXIT createRealTimeMessageINMSGMSGSTREAMINMSGOBJECTSINFOBJEXIT() {
        return new RealTimeMessageIN.MSG.MSGSTREAMIN.MSGOBJECTS.INFOBJEXIT();
    }

    /**
     * Create an instance of {@link RealTimeMessageIN.MSG.MSGSTREAMIN.MSGOBJECTS.INFOBJMUINFO }
     * 
     */
    public RealTimeMessageIN.MSG.MSGSTREAMIN.MSGOBJECTS.INFOBJMUINFO createRealTimeMessageINMSGMSGSTREAMINMSGOBJECTSINFOBJMUINFO() {
        return new RealTimeMessageIN.MSG.MSGSTREAMIN.MSGOBJECTS.INFOBJMUINFO();
    }

    /**
     * Create an instance of {@link RealTimeMessageIN.MSG.MSGSTREAMIN.MSGOBJECTS.INFOBJEQUIPMENT.PLB.USAGE }
     * 
     */
    public RealTimeMessageIN.MSG.MSGSTREAMIN.MSGOBJECTS.INFOBJEQUIPMENT.PLB.USAGE createRealTimeMessageINMSGMSGSTREAMINMSGOBJECTSINFOBJEQUIPMENTPLBUSAGE() {
        return new RealTimeMessageIN.MSG.MSGSTREAMIN.MSGOBJECTS.INFOBJEQUIPMENT.PLB.USAGE();
    }

    /**
     * Create an instance of {@link RealTimeMessageIN.MSG.MSGSTREAMIN.MSGOBJECTS.INFOBJEQUIPMENT.PLB.STATUS }
     * 
     */
    public RealTimeMessageIN.MSG.MSGSTREAMIN.MSGOBJECTS.INFOBJEQUIPMENT.PLB.STATUS createRealTimeMessageINMSGMSGSTREAMINMSGOBJECTSINFOBJEQUIPMENTPLBSTATUS() {
        return new RealTimeMessageIN.MSG.MSGSTREAMIN.MSGOBJECTS.INFOBJEQUIPMENT.PLB.STATUS();
    }

    /**
     * Create an instance of {@link RealTimeMessageIN.MSG.MSGSTREAMIN.MSGOBJECTS.INFOBJMANIFEST.Manifest }
     * 
     */
    public RealTimeMessageIN.MSG.MSGSTREAMIN.MSGOBJECTS.INFOBJMANIFEST.Manifest createRealTimeMessageINMSGMSGSTREAMINMSGOBJECTSINFOBJMANIFESTManifest() {
        return new RealTimeMessageIN.MSG.MSGSTREAMIN.MSGOBJECTS.INFOBJMANIFEST.Manifest();
    }

    /**
     * Create an instance of {@link RealTimeMessageIN.MSG.MSGSTREAMIN.MSGOBJECTS.BULKDATA.METAR }
     * 
     */
    public RealTimeMessageIN.MSG.MSGSTREAMIN.MSGOBJECTS.BULKDATA.METAR createRealTimeMessageINMSGMSGSTREAMINMSGOBJECTSBULKDATAMETAR() {
        return new RealTimeMessageIN.MSG.MSGSTREAMIN.MSGOBJECTS.BULKDATA.METAR();
    }

    /**
     * Create an instance of {@link RealTimeMessageIN.MSG.MSGSTREAMIN.MSGOBJECTS.BULKDATA.SITA }
     * 
     */
    public RealTimeMessageIN.MSG.MSGSTREAMIN.MSGOBJECTS.BULKDATA.SITA createRealTimeMessageINMSGMSGSTREAMINMSGOBJECTSBULKDATASITA() {
        return new RealTimeMessageIN.MSG.MSGSTREAMIN.MSGOBJECTS.BULKDATA.SITA();
    }

    /**
     * Create an instance of {@link RealTimeMessageIN.MSG.MSGSTREAMIN.MSGOBJECTS.BULKDATA.AFTN }
     * 
     */
    public RealTimeMessageIN.MSG.MSGSTREAMIN.MSGOBJECTS.BULKDATA.AFTN createRealTimeMessageINMSGMSGSTREAMINMSGOBJECTSBULKDATAAFTN() {
        return new RealTimeMessageIN.MSG.MSGSTREAMIN.MSGOBJECTS.BULKDATA.AFTN();
    }

    /**
     * Create an instance of {@link RealTimeMessageIN.MSG.MSGSTREAMIN.MSGOBJECTS.CONCAT.TOWINGS }
     * 
     */
    public RealTimeMessageIN.MSG.MSGSTREAMIN.MSGOBJECTS.CONCAT.TOWINGS createRealTimeMessageINMSGMSGSTREAMINMSGOBJECTSCONCATTOWINGS() {
        return new RealTimeMessageIN.MSG.MSGSTREAMIN.MSGOBJECTS.CONCAT.TOWINGS();
    }

    /**
     * Create an instance of {@link RealTimeMessageIN.MSG.MSGSTREAMIN.MSGOBJECTS.STATIC.RESOURCES.COMMONCOUNTERS }
     * 
     */
    public RealTimeMessageIN.MSG.MSGSTREAMIN.MSGOBJECTS.STATIC.RESOURCES.COMMONCOUNTERS createRealTimeMessageINMSGMSGSTREAMINMSGOBJECTSSTATICRESOURCESCOMMONCOUNTERS() {
        return new RealTimeMessageIN.MSG.MSGSTREAMIN.MSGOBJECTS.STATIC.RESOURCES.COMMONCOUNTERS();
    }

    /**
     * Create an instance of {@link RealTimeMessageIN.MSG.MSGSTREAMIN.MSGOBJECTS.STATIC.RESOURCES.COUNTERS.STATICCOUNTER }
     * 
     */
    public RealTimeMessageIN.MSG.MSGSTREAMIN.MSGOBJECTS.STATIC.RESOURCES.COUNTERS.STATICCOUNTER createRealTimeMessageINMSGMSGSTREAMINMSGOBJECTSSTATICRESOURCESCOUNTERSSTATICCOUNTER() {
        return new RealTimeMessageIN.MSG.MSGSTREAMIN.MSGOBJECTS.STATIC.RESOURCES.COUNTERS.STATICCOUNTER();
    }

    /**
     * Create an instance of {@link RealTimeMessageIN.MSG.MSGSTREAMIN.MSGOBJECTS.STATIC.RESOURCES.GATE.STATICGATE }
     * 
     */
    public RealTimeMessageIN.MSG.MSGSTREAMIN.MSGOBJECTS.STATIC.RESOURCES.GATE.STATICGATE createRealTimeMessageINMSGMSGSTREAMINMSGOBJECTSSTATICRESOURCESGATESTATICGATE() {
        return new RealTimeMessageIN.MSG.MSGSTREAMIN.MSGOBJECTS.STATIC.RESOURCES.GATE.STATICGATE();
    }

    /**
     * Create an instance of {@link RealTimeMessageIN.MSG.MSGSTREAMIN.MSGOBJECTS.STATIC.RESOURCES.BELTS.STATICBELT }
     * 
     */
    public RealTimeMessageIN.MSG.MSGSTREAMIN.MSGOBJECTS.STATIC.RESOURCES.BELTS.STATICBELT createRealTimeMessageINMSGMSGSTREAMINMSGOBJECTSSTATICRESOURCESBELTSSTATICBELT() {
        return new RealTimeMessageIN.MSG.MSGSTREAMIN.MSGOBJECTS.STATIC.RESOURCES.BELTS.STATICBELT();
    }

    /**
     * Create an instance of {@link RealTimeMessageIN.MSG.MSGSTREAMIN.MSGOBJECTS.STATIC.RESOURCES.ACPOSITIONS.STATICACPOSITION }
     * 
     */
    public RealTimeMessageIN.MSG.MSGSTREAMIN.MSGOBJECTS.STATIC.RESOURCES.ACPOSITIONS.STATICACPOSITION createRealTimeMessageINMSGMSGSTREAMINMSGOBJECTSSTATICRESOURCESACPOSITIONSSTATICACPOSITION() {
        return new RealTimeMessageIN.MSG.MSGSTREAMIN.MSGOBJECTS.STATIC.RESOURCES.ACPOSITIONS.STATICACPOSITION();
    }

    /**
     * Create an instance of {@link RealTimeMessageIN.MSG.MSGSTREAMIN.MSGOBJECTS.INFOBJVDGS.VDGSARR }
     * 
     */
    public RealTimeMessageIN.MSG.MSGSTREAMIN.MSGOBJECTS.INFOBJVDGS.VDGSARR createRealTimeMessageINMSGMSGSTREAMINMSGOBJECTSINFOBJVDGSVDGSARR() {
        return new RealTimeMessageIN.MSG.MSGSTREAMIN.MSGOBJECTS.INFOBJVDGS.VDGSARR();
    }

    /**
     * Create an instance of {@link RealTimeMessageIN.MSG.MSGSTREAMIN.MSGOBJECTS.INFOBJVDGS.VDGSDEP }
     * 
     */
    public RealTimeMessageIN.MSG.MSGSTREAMIN.MSGOBJECTS.INFOBJVDGS.VDGSDEP createRealTimeMessageINMSGMSGSTREAMINMSGOBJECTSINFOBJVDGSVDGSDEP() {
        return new RealTimeMessageIN.MSG.MSGSTREAMIN.MSGOBJECTS.INFOBJVDGS.VDGSDEP();
    }

    /**
     * Create an instance of {@link RealTimeMessageIN.MSG.MSGSTREAMIN.MSGOBJECTS.INFOBJGATE.GATEARR }
     * 
     */
    public RealTimeMessageIN.MSG.MSGSTREAMIN.MSGOBJECTS.INFOBJGATE.GATEARR createRealTimeMessageINMSGMSGSTREAMINMSGOBJECTSINFOBJGATEGATEARR() {
        return new RealTimeMessageIN.MSG.MSGSTREAMIN.MSGOBJECTS.INFOBJGATE.GATEARR();
    }

    /**
     * Create an instance of {@link RealTimeMessageIN.MSG.MSGSTREAMIN.MSGOBJECTS.INFOBJGATE.GATEDEP }
     * 
     */
    public RealTimeMessageIN.MSG.MSGSTREAMIN.MSGOBJECTS.INFOBJGATE.GATEDEP createRealTimeMessageINMSGMSGSTREAMINMSGOBJECTSINFOBJGATEGATEDEP() {
        return new RealTimeMessageIN.MSG.MSGSTREAMIN.MSGOBJECTS.INFOBJGATE.GATEDEP();
    }

    /**
     * Create an instance of {@link RealTimeMessageIN.MSG.MSGSTREAMIN.MSGOBJECTS.INFOBJACPOSITION.ACPOSITIONARR }
     * 
     */
    public RealTimeMessageIN.MSG.MSGSTREAMIN.MSGOBJECTS.INFOBJACPOSITION.ACPOSITIONARR createRealTimeMessageINMSGMSGSTREAMINMSGOBJECTSINFOBJACPOSITIONACPOSITIONARR() {
        return new RealTimeMessageIN.MSG.MSGSTREAMIN.MSGOBJECTS.INFOBJACPOSITION.ACPOSITIONARR();
    }

    /**
     * Create an instance of {@link RealTimeMessageIN.MSG.MSGSTREAMIN.MSGOBJECTS.INFOBJACPOSITION.ACPOSITIONDEP }
     * 
     */
    public RealTimeMessageIN.MSG.MSGSTREAMIN.MSGOBJECTS.INFOBJACPOSITION.ACPOSITIONDEP createRealTimeMessageINMSGMSGSTREAMINMSGOBJECTSINFOBJACPOSITIONACPOSITIONDEP() {
        return new RealTimeMessageIN.MSG.MSGSTREAMIN.MSGOBJECTS.INFOBJACPOSITION.ACPOSITIONDEP();
    }

    /**
     * Create an instance of {@link sf.sfis.miniesb.esb.realtimeinbound.MSG.MSGSTREAMIN.INFOBJGENERIC }
     * 
     */
    public sf.sfis.miniesb.esb.realtimeinbound.MSG.MSGSTREAMIN.INFOBJGENERIC createMSGMSGSTREAMININFOBJGENERIC() {
        return new sf.sfis.miniesb.esb.realtimeinbound.MSG.MSGSTREAMIN.INFOBJGENERIC();
    }

    /**
     * Create an instance of {@link sf.sfis.miniesb.esb.realtimeinbound.MSG.MSGSTREAMIN.MSGOBJECTS.INFOBJFLIGHT }
     * 
     */
    public sf.sfis.miniesb.esb.realtimeinbound.MSG.MSGSTREAMIN.MSGOBJECTS.INFOBJFLIGHT createMSGMSGSTREAMINMSGOBJECTSINFOBJFLIGHT() {
        return new sf.sfis.miniesb.esb.realtimeinbound.MSG.MSGSTREAMIN.MSGOBJECTS.INFOBJFLIGHT();
    }

    /**
     * Create an instance of {@link sf.sfis.miniesb.esb.realtimeinbound.MSG.MSGSTREAMIN.MSGOBJECTS.INFOBJBELT }
     * 
     */
    public sf.sfis.miniesb.esb.realtimeinbound.MSG.MSGSTREAMIN.MSGOBJECTS.INFOBJBELT createMSGMSGSTREAMINMSGOBJECTSINFOBJBELT() {
        return new sf.sfis.miniesb.esb.realtimeinbound.MSG.MSGSTREAMIN.MSGOBJECTS.INFOBJBELT();
    }

    /**
     * Create an instance of {@link sf.sfis.miniesb.esb.realtimeinbound.MSG.MSGSTREAMIN.MSGOBJECTS.INFOBJCOUNTER }
     * 
     */
    public sf.sfis.miniesb.esb.realtimeinbound.MSG.MSGSTREAMIN.MSGOBJECTS.INFOBJCOUNTER createMSGMSGSTREAMINMSGOBJECTSINFOBJCOUNTER() {
        return new sf.sfis.miniesb.esb.realtimeinbound.MSG.MSGSTREAMIN.MSGOBJECTS.INFOBJCOUNTER();
    }

    /**
     * Create an instance of {@link sf.sfis.miniesb.esb.realtimeinbound.MSG.MSGSTREAMIN.MSGOBJECTS.INFOBJLOUNGE }
     * 
     */
    public sf.sfis.miniesb.esb.realtimeinbound.MSG.MSGSTREAMIN.MSGOBJECTS.INFOBJLOUNGE createMSGMSGSTREAMINMSGOBJECTSINFOBJLOUNGE() {
        return new sf.sfis.miniesb.esb.realtimeinbound.MSG.MSGSTREAMIN.MSGOBJECTS.INFOBJLOUNGE();
    }

    /**
     * Create an instance of {@link sf.sfis.miniesb.esb.realtimeinbound.MSG.MSGSTREAMIN.MSGOBJECTS.INFOBJEXIT }
     * 
     */
    public sf.sfis.miniesb.esb.realtimeinbound.MSG.MSGSTREAMIN.MSGOBJECTS.INFOBJEXIT createMSGMSGSTREAMINMSGOBJECTSINFOBJEXIT() {
        return new sf.sfis.miniesb.esb.realtimeinbound.MSG.MSGSTREAMIN.MSGOBJECTS.INFOBJEXIT();
    }

    /**
     * Create an instance of {@link sf.sfis.miniesb.esb.realtimeinbound.MSG.MSGSTREAMIN.MSGOBJECTS.INFOBJMUINFO }
     * 
     */
    public sf.sfis.miniesb.esb.realtimeinbound.MSG.MSGSTREAMIN.MSGOBJECTS.INFOBJMUINFO createMSGMSGSTREAMINMSGOBJECTSINFOBJMUINFO() {
        return new sf.sfis.miniesb.esb.realtimeinbound.MSG.MSGSTREAMIN.MSGOBJECTS.INFOBJMUINFO();
    }

    /**
     * Create an instance of {@link sf.sfis.miniesb.esb.realtimeinbound.MSG.MSGSTREAMIN.MSGOBJECTS.INFOBJEQUIPMENT.PLB.USAGE }
     * 
     */
    public sf.sfis.miniesb.esb.realtimeinbound.MSG.MSGSTREAMIN.MSGOBJECTS.INFOBJEQUIPMENT.PLB.USAGE createMSGMSGSTREAMINMSGOBJECTSINFOBJEQUIPMENTPLBUSAGE() {
        return new sf.sfis.miniesb.esb.realtimeinbound.MSG.MSGSTREAMIN.MSGOBJECTS.INFOBJEQUIPMENT.PLB.USAGE();
    }

    /**
     * Create an instance of {@link sf.sfis.miniesb.esb.realtimeinbound.MSG.MSGSTREAMIN.MSGOBJECTS.INFOBJEQUIPMENT.PLB.STATUS }
     * 
     */
    public sf.sfis.miniesb.esb.realtimeinbound.MSG.MSGSTREAMIN.MSGOBJECTS.INFOBJEQUIPMENT.PLB.STATUS createMSGMSGSTREAMINMSGOBJECTSINFOBJEQUIPMENTPLBSTATUS() {
        return new sf.sfis.miniesb.esb.realtimeinbound.MSG.MSGSTREAMIN.MSGOBJECTS.INFOBJEQUIPMENT.PLB.STATUS();
    }

    /**
     * Create an instance of {@link sf.sfis.miniesb.esb.realtimeinbound.MSG.MSGSTREAMIN.MSGOBJECTS.INFOBJMANIFEST.Manifest }
     * 
     */
    public sf.sfis.miniesb.esb.realtimeinbound.MSG.MSGSTREAMIN.MSGOBJECTS.INFOBJMANIFEST.Manifest createMSGMSGSTREAMINMSGOBJECTSINFOBJMANIFESTManifest() {
        return new sf.sfis.miniesb.esb.realtimeinbound.MSG.MSGSTREAMIN.MSGOBJECTS.INFOBJMANIFEST.Manifest();
    }

    /**
     * Create an instance of {@link sf.sfis.miniesb.esb.realtimeinbound.MSG.MSGSTREAMIN.MSGOBJECTS.BULKDATA.METAR }
     * 
     */
    public sf.sfis.miniesb.esb.realtimeinbound.MSG.MSGSTREAMIN.MSGOBJECTS.BULKDATA.METAR createMSGMSGSTREAMINMSGOBJECTSBULKDATAMETAR() {
        return new sf.sfis.miniesb.esb.realtimeinbound.MSG.MSGSTREAMIN.MSGOBJECTS.BULKDATA.METAR();
    }

    /**
     * Create an instance of {@link sf.sfis.miniesb.esb.realtimeinbound.MSG.MSGSTREAMIN.MSGOBJECTS.BULKDATA.SITA }
     * 
     */
    public sf.sfis.miniesb.esb.realtimeinbound.MSG.MSGSTREAMIN.MSGOBJECTS.BULKDATA.SITA createMSGMSGSTREAMINMSGOBJECTSBULKDATASITA() {
        return new sf.sfis.miniesb.esb.realtimeinbound.MSG.MSGSTREAMIN.MSGOBJECTS.BULKDATA.SITA();
    }

    /**
     * Create an instance of {@link sf.sfis.miniesb.esb.realtimeinbound.MSG.MSGSTREAMIN.MSGOBJECTS.BULKDATA.AFTN }
     * 
     */
    public sf.sfis.miniesb.esb.realtimeinbound.MSG.MSGSTREAMIN.MSGOBJECTS.BULKDATA.AFTN createMSGMSGSTREAMINMSGOBJECTSBULKDATAAFTN() {
        return new sf.sfis.miniesb.esb.realtimeinbound.MSG.MSGSTREAMIN.MSGOBJECTS.BULKDATA.AFTN();
    }

    /**
     * Create an instance of {@link sf.sfis.miniesb.esb.realtimeinbound.MSG.MSGSTREAMIN.MSGOBJECTS.CONCAT.TOWINGS }
     * 
     */
    public sf.sfis.miniesb.esb.realtimeinbound.MSG.MSGSTREAMIN.MSGOBJECTS.CONCAT.TOWINGS createMSGMSGSTREAMINMSGOBJECTSCONCATTOWINGS() {
        return new sf.sfis.miniesb.esb.realtimeinbound.MSG.MSGSTREAMIN.MSGOBJECTS.CONCAT.TOWINGS();
    }

    /**
     * Create an instance of {@link sf.sfis.miniesb.esb.realtimeinbound.MSG.MSGSTREAMIN.MSGOBJECTS.STATIC.RESOURCES.COMMONCOUNTERS }
     * 
     */
    public sf.sfis.miniesb.esb.realtimeinbound.MSG.MSGSTREAMIN.MSGOBJECTS.STATIC.RESOURCES.COMMONCOUNTERS createMSGMSGSTREAMINMSGOBJECTSSTATICRESOURCESCOMMONCOUNTERS() {
        return new sf.sfis.miniesb.esb.realtimeinbound.MSG.MSGSTREAMIN.MSGOBJECTS.STATIC.RESOURCES.COMMONCOUNTERS();
    }

    /**
     * Create an instance of {@link sf.sfis.miniesb.esb.realtimeinbound.MSG.MSGSTREAMIN.MSGOBJECTS.STATIC.RESOURCES.COUNTERS.STATICCOUNTER }
     * 
     */
    public sf.sfis.miniesb.esb.realtimeinbound.MSG.MSGSTREAMIN.MSGOBJECTS.STATIC.RESOURCES.COUNTERS.STATICCOUNTER createMSGMSGSTREAMINMSGOBJECTSSTATICRESOURCESCOUNTERSSTATICCOUNTER() {
        return new sf.sfis.miniesb.esb.realtimeinbound.MSG.MSGSTREAMIN.MSGOBJECTS.STATIC.RESOURCES.COUNTERS.STATICCOUNTER();
    }

    /**
     * Create an instance of {@link sf.sfis.miniesb.esb.realtimeinbound.MSG.MSGSTREAMIN.MSGOBJECTS.STATIC.RESOURCES.GATE.STATICGATE }
     * 
     */
    public sf.sfis.miniesb.esb.realtimeinbound.MSG.MSGSTREAMIN.MSGOBJECTS.STATIC.RESOURCES.GATE.STATICGATE createMSGMSGSTREAMINMSGOBJECTSSTATICRESOURCESGATESTATICGATE() {
        return new sf.sfis.miniesb.esb.realtimeinbound.MSG.MSGSTREAMIN.MSGOBJECTS.STATIC.RESOURCES.GATE.STATICGATE();
    }

    /**
     * Create an instance of {@link sf.sfis.miniesb.esb.realtimeinbound.MSG.MSGSTREAMIN.MSGOBJECTS.STATIC.RESOURCES.BELTS.STATICBELT }
     * 
     */
    public sf.sfis.miniesb.esb.realtimeinbound.MSG.MSGSTREAMIN.MSGOBJECTS.STATIC.RESOURCES.BELTS.STATICBELT createMSGMSGSTREAMINMSGOBJECTSSTATICRESOURCESBELTSSTATICBELT() {
        return new sf.sfis.miniesb.esb.realtimeinbound.MSG.MSGSTREAMIN.MSGOBJECTS.STATIC.RESOURCES.BELTS.STATICBELT();
    }

    /**
     * Create an instance of {@link sf.sfis.miniesb.esb.realtimeinbound.MSG.MSGSTREAMIN.MSGOBJECTS.STATIC.RESOURCES.ACPOSITIONS.STATICACPOSITION }
     * 
     */
    public sf.sfis.miniesb.esb.realtimeinbound.MSG.MSGSTREAMIN.MSGOBJECTS.STATIC.RESOURCES.ACPOSITIONS.STATICACPOSITION createMSGMSGSTREAMINMSGOBJECTSSTATICRESOURCESACPOSITIONSSTATICACPOSITION() {
        return new sf.sfis.miniesb.esb.realtimeinbound.MSG.MSGSTREAMIN.MSGOBJECTS.STATIC.RESOURCES.ACPOSITIONS.STATICACPOSITION();
    }

    /**
     * Create an instance of {@link sf.sfis.miniesb.esb.realtimeinbound.MSG.MSGSTREAMIN.MSGOBJECTS.INFOBJVDGS.VDGSARR }
     * 
     */
    public sf.sfis.miniesb.esb.realtimeinbound.MSG.MSGSTREAMIN.MSGOBJECTS.INFOBJVDGS.VDGSARR createMSGMSGSTREAMINMSGOBJECTSINFOBJVDGSVDGSARR() {
        return new sf.sfis.miniesb.esb.realtimeinbound.MSG.MSGSTREAMIN.MSGOBJECTS.INFOBJVDGS.VDGSARR();
    }

    /**
     * Create an instance of {@link sf.sfis.miniesb.esb.realtimeinbound.MSG.MSGSTREAMIN.MSGOBJECTS.INFOBJVDGS.VDGSDEP }
     * 
     */
    public sf.sfis.miniesb.esb.realtimeinbound.MSG.MSGSTREAMIN.MSGOBJECTS.INFOBJVDGS.VDGSDEP createMSGMSGSTREAMINMSGOBJECTSINFOBJVDGSVDGSDEP() {
        return new sf.sfis.miniesb.esb.realtimeinbound.MSG.MSGSTREAMIN.MSGOBJECTS.INFOBJVDGS.VDGSDEP();
    }

    /**
     * Create an instance of {@link sf.sfis.miniesb.esb.realtimeinbound.MSG.MSGSTREAMIN.MSGOBJECTS.INFOBJGATE.GATEARR }
     * 
     */
    public sf.sfis.miniesb.esb.realtimeinbound.MSG.MSGSTREAMIN.MSGOBJECTS.INFOBJGATE.GATEARR createMSGMSGSTREAMINMSGOBJECTSINFOBJGATEGATEARR() {
        return new sf.sfis.miniesb.esb.realtimeinbound.MSG.MSGSTREAMIN.MSGOBJECTS.INFOBJGATE.GATEARR();
    }

    /**
     * Create an instance of {@link sf.sfis.miniesb.esb.realtimeinbound.MSG.MSGSTREAMIN.MSGOBJECTS.INFOBJGATE.GATEDEP }
     * 
     */
    public sf.sfis.miniesb.esb.realtimeinbound.MSG.MSGSTREAMIN.MSGOBJECTS.INFOBJGATE.GATEDEP createMSGMSGSTREAMINMSGOBJECTSINFOBJGATEGATEDEP() {
        return new sf.sfis.miniesb.esb.realtimeinbound.MSG.MSGSTREAMIN.MSGOBJECTS.INFOBJGATE.GATEDEP();
    }

    /**
     * Create an instance of {@link sf.sfis.miniesb.esb.realtimeinbound.MSG.MSGSTREAMIN.MSGOBJECTS.INFOBJACPOSITION.ACPOSITIONARR }
     * 
     */
    public sf.sfis.miniesb.esb.realtimeinbound.MSG.MSGSTREAMIN.MSGOBJECTS.INFOBJACPOSITION.ACPOSITIONARR createMSGMSGSTREAMINMSGOBJECTSINFOBJACPOSITIONACPOSITIONARR() {
        return new sf.sfis.miniesb.esb.realtimeinbound.MSG.MSGSTREAMIN.MSGOBJECTS.INFOBJACPOSITION.ACPOSITIONARR();
    }

    /**
     * Create an instance of {@link sf.sfis.miniesb.esb.realtimeinbound.MSG.MSGSTREAMIN.MSGOBJECTS.INFOBJACPOSITION.ACPOSITIONDEP }
     * 
     */
    public sf.sfis.miniesb.esb.realtimeinbound.MSG.MSGSTREAMIN.MSGOBJECTS.INFOBJACPOSITION.ACPOSITIONDEP createMSGMSGSTREAMINMSGOBJECTSINFOBJACPOSITIONACPOSITIONDEP() {
        return new sf.sfis.miniesb.esb.realtimeinbound.MSG.MSGSTREAMIN.MSGOBJECTS.INFOBJACPOSITION.ACPOSITIONDEP();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RealTimeMessageIN.MSG.MSGSTREAMIN.MSGOBJECTS.INFOBJMUINFO }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link RealTimeMessageIN.MSG.MSGSTREAMIN.MSGOBJECTS.INFOBJMUINFO }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "INFOBJ_MUINFO", scope = RealTimeMessageIN.MSG.MSGSTREAMIN.MSGOBJECTS.class)
    public JAXBElement<RealTimeMessageIN.MSG.MSGSTREAMIN.MSGOBJECTS.INFOBJMUINFO> createRealTimeMessageINMSGMSGSTREAMINMSGOBJECTSINFOBJMUINFO(RealTimeMessageIN.MSG.MSGSTREAMIN.MSGOBJECTS.INFOBJMUINFO value) {
        return new JAXBElement<RealTimeMessageIN.MSG.MSGSTREAMIN.MSGOBJECTS.INFOBJMUINFO>(_RealTimeMessageINMSGMSGSTREAMINMSGOBJECTSINFOBJMUINFO_QNAME, RealTimeMessageIN.MSG.MSGSTREAMIN.MSGOBJECTS.INFOBJMUINFO.class, RealTimeMessageIN.MSG.MSGSTREAMIN.MSGOBJECTS.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RealTimeMessageIN.MSG.MSGSTREAMIN.MSGOBJECTS.INFOBJMANIFEST }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link RealTimeMessageIN.MSG.MSGSTREAMIN.MSGOBJECTS.INFOBJMANIFEST }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "INFOBJ_MANIFEST", scope = RealTimeMessageIN.MSG.MSGSTREAMIN.MSGOBJECTS.class)
    public JAXBElement<RealTimeMessageIN.MSG.MSGSTREAMIN.MSGOBJECTS.INFOBJMANIFEST> createRealTimeMessageINMSGMSGSTREAMINMSGOBJECTSINFOBJMANIFEST(RealTimeMessageIN.MSG.MSGSTREAMIN.MSGOBJECTS.INFOBJMANIFEST value) {
        return new JAXBElement<RealTimeMessageIN.MSG.MSGSTREAMIN.MSGOBJECTS.INFOBJMANIFEST>(_RealTimeMessageINMSGMSGSTREAMINMSGOBJECTSINFOBJMANIFEST_QNAME, RealTimeMessageIN.MSG.MSGSTREAMIN.MSGOBJECTS.INFOBJMANIFEST.class, RealTimeMessageIN.MSG.MSGSTREAMIN.MSGOBJECTS.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RealTimeMessageIN.MSG.MSGSTREAMIN.MSGOBJECTS.INFOBJEQUIPMENT }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link RealTimeMessageIN.MSG.MSGSTREAMIN.MSGOBJECTS.INFOBJEQUIPMENT }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "INFOBJ_EQUIPMENT", scope = RealTimeMessageIN.MSG.MSGSTREAMIN.MSGOBJECTS.class)
    public JAXBElement<RealTimeMessageIN.MSG.MSGSTREAMIN.MSGOBJECTS.INFOBJEQUIPMENT> createRealTimeMessageINMSGMSGSTREAMINMSGOBJECTSINFOBJEQUIPMENT(RealTimeMessageIN.MSG.MSGSTREAMIN.MSGOBJECTS.INFOBJEQUIPMENT value) {
        return new JAXBElement<RealTimeMessageIN.MSG.MSGSTREAMIN.MSGOBJECTS.INFOBJEQUIPMENT>(_RealTimeMessageINMSGMSGSTREAMINMSGOBJECTSINFOBJEQUIPMENT_QNAME, RealTimeMessageIN.MSG.MSGSTREAMIN.MSGOBJECTS.INFOBJEQUIPMENT.class, RealTimeMessageIN.MSG.MSGSTREAMIN.MSGOBJECTS.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "BAZ1", scope = RealTimeMessageIN.MSG.MSGSTREAMIN.MSGOBJECTS.INFOBJMUINFO.class)
    public JAXBElement<String> createRealTimeMessageINMSGMSGSTREAMINMSGOBJECTSINFOBJMUINFOBAZ1(String value) {
        return new JAXBElement<String>(_RealTimeMessageINMSGMSGSTREAMINMSGOBJECTSINFOBJMUINFOBAZ1_QNAME, String.class, RealTimeMessageIN.MSG.MSGSTREAMIN.MSGOBJECTS.INFOBJMUINFO.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "BAZ4", scope = RealTimeMessageIN.MSG.MSGSTREAMIN.MSGOBJECTS.INFOBJMUINFO.class)
    public JAXBElement<String> createRealTimeMessageINMSGMSGSTREAMINMSGOBJECTSINFOBJMUINFOBAZ4(String value) {
        return new JAXBElement<String>(_RealTimeMessageINMSGMSGSTREAMINMSGOBJECTSINFOBJMUINFOBAZ4_QNAME, String.class, RealTimeMessageIN.MSG.MSGSTREAMIN.MSGOBJECTS.INFOBJMUINFO.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "BAO1", scope = RealTimeMessageIN.MSG.MSGSTREAMIN.MSGOBJECTS.INFOBJMUINFO.class)
    public JAXBElement<String> createRealTimeMessageINMSGMSGSTREAMINMSGOBJECTSINFOBJMUINFOBAO1(String value) {
        return new JAXBElement<String>(_RealTimeMessageINMSGMSGSTREAMINMSGOBJECTSINFOBJMUINFOBAO1_QNAME, String.class, RealTimeMessageIN.MSG.MSGSTREAMIN.MSGOBJECTS.INFOBJMUINFO.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "BAC1", scope = RealTimeMessageIN.MSG.MSGSTREAMIN.MSGOBJECTS.INFOBJMUINFO.class)
    public JAXBElement<String> createRealTimeMessageINMSGMSGSTREAMINMSGOBJECTSINFOBJMUINFOBAC1(String value) {
        return new JAXBElement<String>(_RealTimeMessageINMSGMSGSTREAMINMSGOBJECTSINFOBJMUINFOBAC1_QNAME, String.class, RealTimeMessageIN.MSG.MSGSTREAMIN.MSGOBJECTS.INFOBJMUINFO.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "BAO4", scope = RealTimeMessageIN.MSG.MSGSTREAMIN.MSGOBJECTS.INFOBJMUINFO.class)
    public JAXBElement<String> createRealTimeMessageINMSGMSGSTREAMINMSGOBJECTSINFOBJMUINFOBAO4(String value) {
        return new JAXBElement<String>(_RealTimeMessageINMSGMSGSTREAMINMSGOBJECTSINFOBJMUINFOBAO4_QNAME, String.class, RealTimeMessageIN.MSG.MSGSTREAMIN.MSGOBJECTS.INFOBJMUINFO.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "BAC4", scope = RealTimeMessageIN.MSG.MSGSTREAMIN.MSGOBJECTS.INFOBJMUINFO.class)
    public JAXBElement<String> createRealTimeMessageINMSGMSGSTREAMINMSGOBJECTSINFOBJMUINFOBAC4(String value) {
        return new JAXBElement<String>(_RealTimeMessageINMSGMSGSTREAMINMSGOBJECTSINFOBJMUINFOBAC4_QNAME, String.class, RealTimeMessageIN.MSG.MSGSTREAMIN.MSGOBJECTS.INFOBJMUINFO.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link sf.sfis.miniesb.esb.realtimeinbound.MSG.MSGSTREAMIN.MSGOBJECTS.INFOBJMUINFO }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link sf.sfis.miniesb.esb.realtimeinbound.MSG.MSGSTREAMIN.MSGOBJECTS.INFOBJMUINFO }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "INFOBJ_MUINFO", scope = sf.sfis.miniesb.esb.realtimeinbound.MSG.MSGSTREAMIN.MSGOBJECTS.class)
    public JAXBElement<sf.sfis.miniesb.esb.realtimeinbound.MSG.MSGSTREAMIN.MSGOBJECTS.INFOBJMUINFO> createMSGMSGSTREAMINMSGOBJECTSINFOBJMUINFO(sf.sfis.miniesb.esb.realtimeinbound.MSG.MSGSTREAMIN.MSGOBJECTS.INFOBJMUINFO value) {
        return new JAXBElement<sf.sfis.miniesb.esb.realtimeinbound.MSG.MSGSTREAMIN.MSGOBJECTS.INFOBJMUINFO>(_RealTimeMessageINMSGMSGSTREAMINMSGOBJECTSINFOBJMUINFO_QNAME, sf.sfis.miniesb.esb.realtimeinbound.MSG.MSGSTREAMIN.MSGOBJECTS.INFOBJMUINFO.class, sf.sfis.miniesb.esb.realtimeinbound.MSG.MSGSTREAMIN.MSGOBJECTS.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link sf.sfis.miniesb.esb.realtimeinbound.MSG.MSGSTREAMIN.MSGOBJECTS.INFOBJMANIFEST }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link sf.sfis.miniesb.esb.realtimeinbound.MSG.MSGSTREAMIN.MSGOBJECTS.INFOBJMANIFEST }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "INFOBJ_MANIFEST", scope = sf.sfis.miniesb.esb.realtimeinbound.MSG.MSGSTREAMIN.MSGOBJECTS.class)
    public JAXBElement<sf.sfis.miniesb.esb.realtimeinbound.MSG.MSGSTREAMIN.MSGOBJECTS.INFOBJMANIFEST> createMSGMSGSTREAMINMSGOBJECTSINFOBJMANIFEST(sf.sfis.miniesb.esb.realtimeinbound.MSG.MSGSTREAMIN.MSGOBJECTS.INFOBJMANIFEST value) {
        return new JAXBElement<sf.sfis.miniesb.esb.realtimeinbound.MSG.MSGSTREAMIN.MSGOBJECTS.INFOBJMANIFEST>(_RealTimeMessageINMSGMSGSTREAMINMSGOBJECTSINFOBJMANIFEST_QNAME, sf.sfis.miniesb.esb.realtimeinbound.MSG.MSGSTREAMIN.MSGOBJECTS.INFOBJMANIFEST.class, sf.sfis.miniesb.esb.realtimeinbound.MSG.MSGSTREAMIN.MSGOBJECTS.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link sf.sfis.miniesb.esb.realtimeinbound.MSG.MSGSTREAMIN.MSGOBJECTS.INFOBJEQUIPMENT }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link sf.sfis.miniesb.esb.realtimeinbound.MSG.MSGSTREAMIN.MSGOBJECTS.INFOBJEQUIPMENT }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "INFOBJ_EQUIPMENT", scope = sf.sfis.miniesb.esb.realtimeinbound.MSG.MSGSTREAMIN.MSGOBJECTS.class)
    public JAXBElement<sf.sfis.miniesb.esb.realtimeinbound.MSG.MSGSTREAMIN.MSGOBJECTS.INFOBJEQUIPMENT> createMSGMSGSTREAMINMSGOBJECTSINFOBJEQUIPMENT(sf.sfis.miniesb.esb.realtimeinbound.MSG.MSGSTREAMIN.MSGOBJECTS.INFOBJEQUIPMENT value) {
        return new JAXBElement<sf.sfis.miniesb.esb.realtimeinbound.MSG.MSGSTREAMIN.MSGOBJECTS.INFOBJEQUIPMENT>(_RealTimeMessageINMSGMSGSTREAMINMSGOBJECTSINFOBJEQUIPMENT_QNAME, sf.sfis.miniesb.esb.realtimeinbound.MSG.MSGSTREAMIN.MSGOBJECTS.INFOBJEQUIPMENT.class, sf.sfis.miniesb.esb.realtimeinbound.MSG.MSGSTREAMIN.MSGOBJECTS.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "BAZ1", scope = sf.sfis.miniesb.esb.realtimeinbound.MSG.MSGSTREAMIN.MSGOBJECTS.INFOBJMUINFO.class)
    public JAXBElement<String> createMSGMSGSTREAMINMSGOBJECTSINFOBJMUINFOBAZ1(String value) {
        return new JAXBElement<String>(_RealTimeMessageINMSGMSGSTREAMINMSGOBJECTSINFOBJMUINFOBAZ1_QNAME, String.class, sf.sfis.miniesb.esb.realtimeinbound.MSG.MSGSTREAMIN.MSGOBJECTS.INFOBJMUINFO.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "BAZ4", scope = sf.sfis.miniesb.esb.realtimeinbound.MSG.MSGSTREAMIN.MSGOBJECTS.INFOBJMUINFO.class)
    public JAXBElement<String> createMSGMSGSTREAMINMSGOBJECTSINFOBJMUINFOBAZ4(String value) {
        return new JAXBElement<String>(_RealTimeMessageINMSGMSGSTREAMINMSGOBJECTSINFOBJMUINFOBAZ4_QNAME, String.class, sf.sfis.miniesb.esb.realtimeinbound.MSG.MSGSTREAMIN.MSGOBJECTS.INFOBJMUINFO.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "BAO1", scope = sf.sfis.miniesb.esb.realtimeinbound.MSG.MSGSTREAMIN.MSGOBJECTS.INFOBJMUINFO.class)
    public JAXBElement<String> createMSGMSGSTREAMINMSGOBJECTSINFOBJMUINFOBAO1(String value) {
        return new JAXBElement<String>(_RealTimeMessageINMSGMSGSTREAMINMSGOBJECTSINFOBJMUINFOBAO1_QNAME, String.class, sf.sfis.miniesb.esb.realtimeinbound.MSG.MSGSTREAMIN.MSGOBJECTS.INFOBJMUINFO.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "BAC1", scope = sf.sfis.miniesb.esb.realtimeinbound.MSG.MSGSTREAMIN.MSGOBJECTS.INFOBJMUINFO.class)
    public JAXBElement<String> createMSGMSGSTREAMINMSGOBJECTSINFOBJMUINFOBAC1(String value) {
        return new JAXBElement<String>(_RealTimeMessageINMSGMSGSTREAMINMSGOBJECTSINFOBJMUINFOBAC1_QNAME, String.class, sf.sfis.miniesb.esb.realtimeinbound.MSG.MSGSTREAMIN.MSGOBJECTS.INFOBJMUINFO.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "BAO4", scope = sf.sfis.miniesb.esb.realtimeinbound.MSG.MSGSTREAMIN.MSGOBJECTS.INFOBJMUINFO.class)
    public JAXBElement<String> createMSGMSGSTREAMINMSGOBJECTSINFOBJMUINFOBAO4(String value) {
        return new JAXBElement<String>(_RealTimeMessageINMSGMSGSTREAMINMSGOBJECTSINFOBJMUINFOBAO4_QNAME, String.class, sf.sfis.miniesb.esb.realtimeinbound.MSG.MSGSTREAMIN.MSGOBJECTS.INFOBJMUINFO.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "BAC4", scope = sf.sfis.miniesb.esb.realtimeinbound.MSG.MSGSTREAMIN.MSGOBJECTS.INFOBJMUINFO.class)
    public JAXBElement<String> createMSGMSGSTREAMINMSGOBJECTSINFOBJMUINFOBAC4(String value) {
        return new JAXBElement<String>(_RealTimeMessageINMSGMSGSTREAMINMSGOBJECTSINFOBJMUINFOBAC4_QNAME, String.class, sf.sfis.miniesb.esb.realtimeinbound.MSG.MSGSTREAMIN.MSGOBJECTS.INFOBJMUINFO.class, value);
    }

}
