//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.05.19 at 12:07:30 PM ICT 
//


package sf.sfis.ifimsconnect.esb.filereadyout;

import jakarta.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the sf.sfis.ifimsconnect.esb package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: sf.sfis.ifimsconnect.esb
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link sf.sfis.ifimsconnect.esb.MSG }
     * 
     */
    public sf.sfis.ifimsconnect.esb.filereadyout.MSG createMSG() {
        return new sf.sfis.ifimsconnect.esb.filereadyout.MSG();
    }

    /**
     * Create an instance of {@link FileTransferOUT }
     * 
     */
    public FileTransferOUT createFileTransferOUT() {
        return new FileTransferOUT();
    }

    /**
     * Create an instance of {@link FileTransferOUT.MSG }
     * 
     */
    public FileTransferOUT.MSG createFileTransferOUTMSG() {
        return new FileTransferOUT.MSG();
    }

    /**
     * Create an instance of {@link FileTransferOUT.MSG.BATCHFILEOUT }
     * 
     */
    public FileTransferOUT.MSG.BATCHFILEOUT createFileTransferOUTMSGBATCHFILEOUT() {
        return new FileTransferOUT.MSG.BATCHFILEOUT();
    }

    /**
     * Create an instance of {@link sf.sfis.ifimsconnect.esb.MSG.BATCHFILEOUT }
     * 
     */
    public sf.sfis.ifimsconnect.esb.filereadyout.MSG.BATCHFILEOUT createMSGBATCHFILEOUT() {
        return new sf.sfis.ifimsconnect.esb.filereadyout.MSG.BATCHFILEOUT();
    }

    /**
     * Create an instance of {@link FileTransferOUT.MSG.BATCHFILEOUT.INFOBJFILEOUT }
     * 
     */
    public FileTransferOUT.MSG.BATCHFILEOUT.INFOBJFILEOUT createFileTransferOUTMSGBATCHFILEOUTINFOBJFILEOUT() {
        return new FileTransferOUT.MSG.BATCHFILEOUT.INFOBJFILEOUT();
    }

    /**
     * Create an instance of {@link sf.sfis.ifimsconnect.esb.MSG.BATCHFILEOUT.INFOBJFILEOUT }
     * 
     */
    public sf.sfis.ifimsconnect.esb.filereadyout.MSG.BATCHFILEOUT.INFOBJFILEOUT createMSGBATCHFILEOUTINFOBJFILEOUT() {
        return new sf.sfis.ifimsconnect.esb.filereadyout.MSG.BATCHFILEOUT.INFOBJFILEOUT();
    }

}
