//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.05.26 at 04:00:07 PM ICT 
//


package sf.sfis.miniesb.esb;

import jakarta.xml.bind.JAXBElement;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlElementRef;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for MSG_RETURN complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="MSG_RETURN">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="MSG">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="MSGORIGIN" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="TIME" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="ACKTYPE" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="NACKDETAIL" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="faultcode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="faultstring" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="faultactor" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="faultdetail" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="MESSAGE" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "MSG_RETURN", propOrder = {
    "msg"
})
public class MSGRETURN {

    @XmlElement(name = "MSG", required = true, nillable = true)
    protected MSGRETURN.MSG msg;

    /**
     * Gets the value of the msg property.
     * 
     * @return
     *     possible object is
     *     {@link MSGRETURN.MSG }
     *     
     */
    public MSGRETURN.MSG getMSG() {
        return msg;
    }

    /**
     * Sets the value of the msg property.
     * 
     * @param value
     *     allowed object is
     *     {@link MSGRETURN.MSG }
     *     
     */
    public void setMSG(MSGRETURN.MSG value) {
        this.msg = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="MSGORIGIN" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="TIME" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="ACKTYPE" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="NACKDETAIL" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="faultcode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                   &lt;element name="faultstring" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                   &lt;element name="faultactor" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                   &lt;element name="faultdetail" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="MESSAGE" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "msgorigin",
        "time",
        "acktype",
        "nackdetail",
        "message"
    })
    public static class MSG {

        @XmlElement(name = "MSGORIGIN", required = true, nillable = true)
        protected String msgorigin;
        @XmlElement(name = "TIME", required = true, nillable = true)
        protected String time;
        @XmlElement(name = "ACKTYPE", required = true, nillable = true)
        protected String acktype;
        @XmlElementRef(name = "NACKDETAIL", type = JAXBElement.class, required = false)
        protected JAXBElement<MSGRETURN.MSG.NACKDETAIL> nackdetail;
        @XmlElement(name = "MESSAGE", required = true, nillable = true)
        protected String message;

        /**
         * Gets the value of the msgorigin property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getMSGORIGIN() {
            return msgorigin;
        }

        /**
         * Sets the value of the msgorigin property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setMSGORIGIN(String value) {
            this.msgorigin = value;
        }

        /**
         * Gets the value of the time property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getTIME() {
            return time;
        }

        /**
         * Sets the value of the time property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setTIME(String value) {
            this.time = value;
        }

        /**
         * Gets the value of the acktype property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getACKTYPE() {
            return acktype;
        }

        /**
         * Sets the value of the acktype property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setACKTYPE(String value) {
            this.acktype = value;
        }

        /**
         * Gets the value of the nackdetail property.
         * 
         * @return
         *     possible object is
         *     {@link JAXBElement }{@code <}{@link MSGRETURN.MSG.NACKDETAIL }{@code >}
         *     
         */
        public JAXBElement<MSGRETURN.MSG.NACKDETAIL> getNACKDETAIL() {
            return nackdetail;
        }

        /**
         * Sets the value of the nackdetail property.
         * 
         * @param value
         *     allowed object is
         *     {@link JAXBElement }{@code <}{@link MSGRETURN.MSG.NACKDETAIL }{@code >}
         *     
         */
        public void setNACKDETAIL(JAXBElement<MSGRETURN.MSG.NACKDETAIL> value) {
            this.nackdetail = value;
        }

        /**
         * Gets the value of the message property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getMESSAGE() {
            return message;
        }

        /**
         * Sets the value of the message property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setMESSAGE(String value) {
            this.message = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="faultcode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="faultstring" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="faultactor" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="faultdetail" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "faultcode",
            "faultstring",
            "faultactor",
            "faultdetail"
        })
        public static class NACKDETAIL {

            @XmlElementRef(name = "faultcode", type = JAXBElement.class, required = false)
            protected JAXBElement<String> faultcode;
            @XmlElementRef(name = "faultstring", type = JAXBElement.class, required = false)
            protected JAXBElement<String> faultstring;
            @XmlElementRef(name = "faultactor", type = JAXBElement.class, required = false)
            protected JAXBElement<String> faultactor;
            @XmlElementRef(name = "faultdetail", type = JAXBElement.class, required = false)
            protected JAXBElement<String> faultdetail;

            /**
             * Gets the value of the faultcode property.
             * 
             * @return
             *     possible object is
             *     {@link JAXBElement }{@code <}{@link String }{@code >}
             *     
             */
            public JAXBElement<String> getFaultcode() {
                return faultcode;
            }

            /**
             * Sets the value of the faultcode property.
             * 
             * @param value
             *     allowed object is
             *     {@link JAXBElement }{@code <}{@link String }{@code >}
             *     
             */
            public void setFaultcode(JAXBElement<String> value) {
                this.faultcode = value;
            }

            /**
             * Gets the value of the faultstring property.
             * 
             * @return
             *     possible object is
             *     {@link JAXBElement }{@code <}{@link String }{@code >}
             *     
             */
            public JAXBElement<String> getFaultstring() {
                return faultstring;
            }

            /**
             * Sets the value of the faultstring property.
             * 
             * @param value
             *     allowed object is
             *     {@link JAXBElement }{@code <}{@link String }{@code >}
             *     
             */
            public void setFaultstring(JAXBElement<String> value) {
                this.faultstring = value;
            }

            /**
             * Gets the value of the faultactor property.
             * 
             * @return
             *     possible object is
             *     {@link JAXBElement }{@code <}{@link String }{@code >}
             *     
             */
            public JAXBElement<String> getFaultactor() {
                return faultactor;
            }

            /**
             * Sets the value of the faultactor property.
             * 
             * @param value
             *     allowed object is
             *     {@link JAXBElement }{@code <}{@link String }{@code >}
             *     
             */
            public void setFaultactor(JAXBElement<String> value) {
                this.faultactor = value;
            }

            /**
             * Gets the value of the faultdetail property.
             * 
             * @return
             *     possible object is
             *     {@link JAXBElement }{@code <}{@link String }{@code >}
             *     
             */
            public JAXBElement<String> getFaultdetail() {
                return faultdetail;
            }

            /**
             * Sets the value of the faultdetail property.
             * 
             * @param value
             *     allowed object is
             *     {@link JAXBElement }{@code <}{@link String }{@code >}
             *     
             */
            public void setFaultdetail(JAXBElement<String> value) {
                this.faultdetail = value;
            }

        }

    }

}
