//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.05.26 at 04:00:07 PM ICT 
//


package sf.sfis.miniesb.esb;

import jakarta.xml.bind.JAXBElement;
import jakarta.xml.bind.annotation.XmlElementDecl;
import jakarta.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the esb package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _MSGRETURNMSGNACKDETAIL_QNAME = new QName("", "NACKDETAIL");
    private final static QName _MSGNACKDETAILFaultactor_QNAME = new QName("", "faultactor");
    private final static QName _MSGNACKDETAILFaultcode_QNAME = new QName("", "faultcode");
    private final static QName _MSGNACKDETAILFaultstring_QNAME = new QName("", "faultstring");
    private final static QName _MSGNACKDETAILFaultdetail_QNAME = new QName("", "faultdetail");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: esb
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link sf.sfis.miniesb.esb.MSG }
     * 
     */
    public sf.sfis.miniesb.esb.MSG createMSG() {
        return new sf.sfis.miniesb.esb.MSG();
    }

    /**
     * Create an instance of {@link MSGRETURN }
     * 
     */
    public MSGRETURN createMSGRETURN() {
        return new MSGRETURN();
    }

    /**
     * Create an instance of {@link MSGRETURN.MSG }
     * 
     */
    public MSGRETURN.MSG createMSGRETURNMSG() {
        return new MSGRETURN.MSG();
    }

    /**
     * Create an instance of {@link sf.sfis.miniesb.esb.MSG.NACKDETAIL }
     * 
     */
    public sf.sfis.miniesb.esb.MSG.NACKDETAIL createMSGNACKDETAIL() {
        return new sf.sfis.miniesb.esb.MSG.NACKDETAIL();
    }

    /**
     * Create an instance of {@link MSGRETURN.MSG.NACKDETAIL }
     * 
     */
    public MSGRETURN.MSG.NACKDETAIL createMSGRETURNMSGNACKDETAIL() {
        return new MSGRETURN.MSG.NACKDETAIL();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MSGRETURN.MSG.NACKDETAIL }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "NACKDETAIL", scope = MSGRETURN.MSG.class)
    public JAXBElement<MSGRETURN.MSG.NACKDETAIL> createMSGRETURNMSGNACKDETAIL(MSGRETURN.MSG.NACKDETAIL value) {
        return new JAXBElement<MSGRETURN.MSG.NACKDETAIL>(_MSGRETURNMSGNACKDETAIL_QNAME, MSGRETURN.MSG.NACKDETAIL.class, MSGRETURN.MSG.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "faultactor", scope = sf.sfis.miniesb.esb.MSG.NACKDETAIL.class)
    public JAXBElement<String> createMSGNACKDETAILFaultactor(String value) {
        return new JAXBElement<String>(_MSGNACKDETAILFaultactor_QNAME, String.class, sf.sfis.miniesb.esb.MSG.NACKDETAIL.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "faultcode", scope = sf.sfis.miniesb.esb.MSG.NACKDETAIL.class)
    public JAXBElement<String> createMSGNACKDETAILFaultcode(String value) {
        return new JAXBElement<String>(_MSGNACKDETAILFaultcode_QNAME, String.class, sf.sfis.miniesb.esb.MSG.NACKDETAIL.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "faultstring", scope = sf.sfis.miniesb.esb.MSG.NACKDETAIL.class)
    public JAXBElement<String> createMSGNACKDETAILFaultstring(String value) {
        return new JAXBElement<String>(_MSGNACKDETAILFaultstring_QNAME, String.class, sf.sfis.miniesb.esb.MSG.NACKDETAIL.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "faultdetail", scope = sf.sfis.miniesb.esb.MSG.NACKDETAIL.class)
    public JAXBElement<String> createMSGNACKDETAILFaultdetail(String value) {
        return new JAXBElement<String>(_MSGNACKDETAILFaultdetail_QNAME, String.class, sf.sfis.miniesb.esb.MSG.NACKDETAIL.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "faultactor", scope = MSGRETURN.MSG.NACKDETAIL.class)
    public JAXBElement<String> createMSGRETURNMSGNACKDETAILFaultactor(String value) {
        return new JAXBElement<String>(_MSGNACKDETAILFaultactor_QNAME, String.class, MSGRETURN.MSG.NACKDETAIL.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "faultcode", scope = MSGRETURN.MSG.NACKDETAIL.class)
    public JAXBElement<String> createMSGRETURNMSGNACKDETAILFaultcode(String value) {
        return new JAXBElement<String>(_MSGNACKDETAILFaultcode_QNAME, String.class, MSGRETURN.MSG.NACKDETAIL.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "faultstring", scope = MSGRETURN.MSG.NACKDETAIL.class)
    public JAXBElement<String> createMSGRETURNMSGNACKDETAILFaultstring(String value) {
        return new JAXBElement<String>(_MSGNACKDETAILFaultstring_QNAME, String.class, MSGRETURN.MSG.NACKDETAIL.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "faultdetail", scope = MSGRETURN.MSG.NACKDETAIL.class)
    public JAXBElement<String> createMSGRETURNMSGNACKDETAILFaultdetail(String value) {
        return new JAXBElement<String>(_MSGNACKDETAILFaultdetail_QNAME, String.class, MSGRETURN.MSG.NACKDETAIL.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link sf.sfis.miniesb.esb.MSG.NACKDETAIL }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "NACKDETAIL", scope = sf.sfis.miniesb.esb.MSG.class)
    public JAXBElement<sf.sfis.miniesb.esb.MSG.NACKDETAIL> createMSGNACKDETAIL(sf.sfis.miniesb.esb.MSG.NACKDETAIL value) {
        return new JAXBElement<sf.sfis.miniesb.esb.MSG.NACKDETAIL>(_MSGRETURNMSGNACKDETAIL_QNAME, sf.sfis.miniesb.esb.MSG.NACKDETAIL.class, sf.sfis.miniesb.esb.MSG.class, value);
    }

}
