//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.05.21 at 09:22:12 AM ICT 
//


package sf.sfis.miniesb.aodb;

import jakarta.xml.bind.JAXBElement;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlElementRef;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all minOccurs="0">
 *         &lt;element name="iam_action" type="{}aodbstring" minOccurs="0"/>
 *         &lt;element name="iam_adep" type="{}aodbstring" minOccurs="0"/>
 *         &lt;element name="iam_ades" type="{}aodbstring" minOccurs="0"/>
 *         &lt;element name="iam_adexpcomment" type="{}aodbstring" minOccurs="0"/>
 *         &lt;element name="iam_arcid" type="{}aodbstring" minOccurs="0"/>
 *         &lt;element name="iam_arctyp" type="{}aodbstring" minOccurs="0"/>
 *         &lt;element name="iam_arrdepind" type="{}aodbstring" minOccurs="0"/>
 *         &lt;element name="iam_asat" type="{}aodbduration" minOccurs="0"/>
 *         &lt;element name="iam_asrt" type="{}aodbduration" minOccurs="0"/>
 *         &lt;element name="iam_atot" type="{}aodbduration" minOccurs="0"/>
 *         &lt;element name="iam_callsign" type="{}aodbstring" minOccurs="0"/>
 *         &lt;element name="iam_checktime" type="{}aodbduration" minOccurs="0"/>
 *         &lt;element name="iam_checkuser" type="{}aodbstring" minOccurs="0"/>
 *         &lt;element name="iam_cnl" type="{}aodbduration" minOccurs="0"/>
 *         &lt;element name="iam_comment" type="{}aodbstring" minOccurs="0"/>
 *         &lt;element name="iam_createtime" type="{}aodbduration" minOccurs="0"/>
 *         &lt;element name="iam_editedmessage" type="{}aodbstring" minOccurs="0"/>
 *         &lt;element name="iam_eobt" type="{}aodbduration" minOccurs="0"/>
 *         &lt;element name="iam_errorcolumn" type="{}aodbinteger" minOccurs="0"/>
 *         &lt;element name="iam_errorlineno" type="{}aodbinteger" minOccurs="0"/>
 *         &lt;element name="iam_errormessage" type="{}aodbstring" minOccurs="0"/>
 *         &lt;element name="iam_etime" type="{}aodbduration" minOccurs="0"/>
 *         &lt;element name="iam_ett" type="{}aodbduration" minOccurs="0"/>
 *         &lt;element name="iam_filtim" type="{}aodbduration" minOccurs="0"/>
 *         &lt;element name="iam_fltrul" type="{}aodbstring" minOccurs="0"/>
 *         &lt;element name="iam_fltsrc" type="{}aodbstring" minOccurs="0"/>
 *         &lt;element name="iam_flttyp" type="{}aodbstring" minOccurs="0"/>
 *         &lt;element name="iam_fplcat" type="{}aodbstring" minOccurs="0"/>
 *         &lt;element name="iam_hovtm" type="{}aodbduration" minOccurs="0"/>
 *         &lt;element name="iam_idseq" type="{}aodbfloat" minOccurs="0"/>
 *         &lt;element name="iam_ifplid" type="{}aodbstring" minOccurs="0"/>
 *         &lt;element name="iam_iobt" type="{}aodbduration" minOccurs="0"/>
 *         &lt;element name="iam_lfztypcode5l" type="{}aodbstring" minOccurs="0"/>
 *         &lt;element name="iam_messagetitle" type="{}aodbstring" minOccurs="0"/>
 *         &lt;element name="iam_modtime" type="{}aodbduration" minOccurs="0"/>
 *         &lt;element name="iam_moduser" type="{}aodbstring" minOccurs="0"/>
 *         &lt;element name="iam_originalmessage" type="{}aodbstring" minOccurs="0"/>
 *         &lt;element name="iam_passive" type="{}aodbduration" minOccurs="0"/>
 *         &lt;element name="iam_reason" type="{}aodbstring" minOccurs="0"/>
 *         &lt;element name="iam_recipient" type="{}aodbstring" minOccurs="0"/>
 *         &lt;element name="iam_registration" type="{}aodbstring" minOccurs="0"/>
 *         &lt;element name="iam_route" type="{}aodbstring" minOccurs="0"/>
 *         &lt;element name="iam_rwy1dir" type="{}aodbstring" minOccurs="0"/>
 *         &lt;element name="iam_rwy2dir" type="{}aodbstring" minOccurs="0"/>
 *         &lt;element name="iam_rwydep" type="{}aodbstring" minOccurs="0"/>
 *         &lt;element name="iam_sender" type="{}aodbstring" minOccurs="0"/>
 *         &lt;element name="iam_seqnum" type="{}aodbstring" minOccurs="0"/>
 *         &lt;element name="iam_sequencenum" type="{}aodbinteger" minOccurs="0"/>
 *         &lt;element name="iam_sequencetime" type="{}aodbduration" minOccurs="0"/>
 *         &lt;element name="iam_severity" type="{}aodbstring" minOccurs="0"/>
 *         &lt;element name="iam_sid" type="{}aodbstring" minOccurs="0"/>
 *         &lt;element name="iam_slottime" type="{}aodbduration" minOccurs="0"/>
 *         &lt;element name="iam_slot_from" type="{}aodbduration" minOccurs="0"/>
 *         &lt;element name="iam_slot_to" type="{}aodbduration" minOccurs="0"/>
 *         &lt;element name="iam_ssrcode" type="{}aodbstring" minOccurs="0"/>
 *         &lt;element name="iam_star" type="{}aodbstring" minOccurs="0"/>
 *         &lt;element name="iam_startupgiventime" type="{}aodbduration" minOccurs="0"/>
 *         &lt;element name="iam_status" type="{}aodbstring" minOccurs="0"/>
 *         &lt;element name="iam_taxitime" type="{}aodbinteger" minOccurs="0"/>
 *         &lt;element name="iam_title" type="{}aodbstring" minOccurs="0"/>
 *         &lt;element name="iam_wktrc" type="{}aodbstring" minOccurs="0"/>
 *         &lt;element name="iam_xmlmessage" type="{}aodbstring" minOccurs="0"/>
 *         &lt;element name="iam_pa_arrival" type="{}aodbinteger" minOccurs="0"/>
 *         &lt;element name="iam_pd_departure" type="{}aodbinteger" minOccurs="0"/>
 *         &lt;element name="iam_syst_station" type="{}aodbstring" minOccurs="0"/>
 *       &lt;/all>
 *       &lt;attribute name="action" type="{}actionType" />
 *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {

})
@XmlRootElement(name = "if_adexpmessage")
public class IfAdexpmessage {

    @XmlElementRef(name = "iam_action", type = JAXBElement.class, required = false)
    protected JAXBElement<Aodbstring> iamAction;
    @XmlElementRef(name = "iam_adep", type = JAXBElement.class, required = false)
    protected JAXBElement<Aodbstring> iamAdep;
    @XmlElementRef(name = "iam_ades", type = JAXBElement.class, required = false)
    protected JAXBElement<Aodbstring> iamAdes;
    @XmlElementRef(name = "iam_adexpcomment", type = JAXBElement.class, required = false)
    protected JAXBElement<Aodbstring> iamAdexpcomment;
    @XmlElementRef(name = "iam_arcid", type = JAXBElement.class, required = false)
    protected JAXBElement<Aodbstring> iamArcid;
    @XmlElementRef(name = "iam_arctyp", type = JAXBElement.class, required = false)
    protected JAXBElement<Aodbstring> iamArctyp;
    @XmlElementRef(name = "iam_arrdepind", type = JAXBElement.class, required = false)
    protected JAXBElement<Aodbstring> iamArrdepind;
    @XmlElementRef(name = "iam_asat", type = JAXBElement.class, required = false)
    protected JAXBElement<Aodbduration> iamAsat;
    @XmlElementRef(name = "iam_asrt", type = JAXBElement.class, required = false)
    protected JAXBElement<Aodbduration> iamAsrt;
    @XmlElementRef(name = "iam_atot", type = JAXBElement.class, required = false)
    protected JAXBElement<Aodbduration> iamAtot;
    @XmlElementRef(name = "iam_callsign", type = JAXBElement.class, required = false)
    protected JAXBElement<Aodbstring> iamCallsign;
    @XmlElementRef(name = "iam_checktime", type = JAXBElement.class, required = false)
    protected JAXBElement<Aodbduration> iamChecktime;
    @XmlElementRef(name = "iam_checkuser", type = JAXBElement.class, required = false)
    protected JAXBElement<Aodbstring> iamCheckuser;
    @XmlElementRef(name = "iam_cnl", type = JAXBElement.class, required = false)
    protected JAXBElement<Aodbduration> iamCnl;
    @XmlElementRef(name = "iam_comment", type = JAXBElement.class, required = false)
    protected JAXBElement<Aodbstring> iamComment;
    @XmlElementRef(name = "iam_createtime", type = JAXBElement.class, required = false)
    protected JAXBElement<Aodbduration> iamCreatetime;
    @XmlElementRef(name = "iam_editedmessage", type = JAXBElement.class, required = false)
    protected JAXBElement<Aodbstring> iamEditedmessage;
    @XmlElementRef(name = "iam_eobt", type = JAXBElement.class, required = false)
    protected JAXBElement<Aodbduration> iamEobt;
    @XmlElementRef(name = "iam_errorcolumn", type = JAXBElement.class, required = false)
    protected JAXBElement<Aodbinteger> iamErrorcolumn;
    @XmlElementRef(name = "iam_errorlineno", type = JAXBElement.class, required = false)
    protected JAXBElement<Aodbinteger> iamErrorlineno;
    @XmlElementRef(name = "iam_errormessage", type = JAXBElement.class, required = false)
    protected JAXBElement<Aodbstring> iamErrormessage;
    @XmlElementRef(name = "iam_etime", type = JAXBElement.class, required = false)
    protected JAXBElement<Aodbduration> iamEtime;
    @XmlElementRef(name = "iam_ett", type = JAXBElement.class, required = false)
    protected JAXBElement<Aodbduration> iamEtt;
    @XmlElementRef(name = "iam_filtim", type = JAXBElement.class, required = false)
    protected JAXBElement<Aodbduration> iamFiltim;
    @XmlElementRef(name = "iam_fltrul", type = JAXBElement.class, required = false)
    protected JAXBElement<Aodbstring> iamFltrul;
    @XmlElementRef(name = "iam_fltsrc", type = JAXBElement.class, required = false)
    protected JAXBElement<Aodbstring> iamFltsrc;
    @XmlElementRef(name = "iam_flttyp", type = JAXBElement.class, required = false)
    protected JAXBElement<Aodbstring> iamFlttyp;
    @XmlElementRef(name = "iam_fplcat", type = JAXBElement.class, required = false)
    protected JAXBElement<Aodbstring> iamFplcat;
    @XmlElementRef(name = "iam_hovtm", type = JAXBElement.class, required = false)
    protected JAXBElement<Aodbduration> iamHovtm;
    @XmlElementRef(name = "iam_idseq", type = JAXBElement.class, required = false)
    protected JAXBElement<Aodbfloat> iamIdseq;
    @XmlElementRef(name = "iam_ifplid", type = JAXBElement.class, required = false)
    protected JAXBElement<Aodbstring> iamIfplid;
    @XmlElementRef(name = "iam_iobt", type = JAXBElement.class, required = false)
    protected JAXBElement<Aodbduration> iamIobt;
    @XmlElementRef(name = "iam_lfztypcode5l", type = JAXBElement.class, required = false)
    protected JAXBElement<Aodbstring> iamLfztypcode5L;
    @XmlElementRef(name = "iam_messagetitle", type = JAXBElement.class, required = false)
    protected JAXBElement<Aodbstring> iamMessagetitle;
    @XmlElementRef(name = "iam_modtime", type = JAXBElement.class, required = false)
    protected JAXBElement<Aodbduration> iamModtime;
    @XmlElementRef(name = "iam_moduser", type = JAXBElement.class, required = false)
    protected JAXBElement<Aodbstring> iamModuser;
    @XmlElementRef(name = "iam_originalmessage", type = JAXBElement.class, required = false)
    protected JAXBElement<Aodbstring> iamOriginalmessage;
    @XmlElementRef(name = "iam_passive", type = JAXBElement.class, required = false)
    protected JAXBElement<Aodbduration> iamPassive;
    @XmlElementRef(name = "iam_reason", type = JAXBElement.class, required = false)
    protected JAXBElement<Aodbstring> iamReason;
    @XmlElementRef(name = "iam_recipient", type = JAXBElement.class, required = false)
    protected JAXBElement<Aodbstring> iamRecipient;
    @XmlElementRef(name = "iam_registration", type = JAXBElement.class, required = false)
    protected JAXBElement<Aodbstring> iamRegistration;
    @XmlElementRef(name = "iam_route", type = JAXBElement.class, required = false)
    protected JAXBElement<Aodbstring> iamRoute;
    @XmlElementRef(name = "iam_rwy1dir", type = JAXBElement.class, required = false)
    protected JAXBElement<Aodbstring> iamRwy1Dir;
    @XmlElementRef(name = "iam_rwy2dir", type = JAXBElement.class, required = false)
    protected JAXBElement<Aodbstring> iamRwy2Dir;
    @XmlElementRef(name = "iam_rwydep", type = JAXBElement.class, required = false)
    protected JAXBElement<Aodbstring> iamRwydep;
    @XmlElementRef(name = "iam_sender", type = JAXBElement.class, required = false)
    protected JAXBElement<Aodbstring> iamSender;
    @XmlElementRef(name = "iam_seqnum", type = JAXBElement.class, required = false)
    protected JAXBElement<Aodbstring> iamSeqnum;
    @XmlElementRef(name = "iam_sequencenum", type = JAXBElement.class, required = false)
    protected JAXBElement<Aodbinteger> iamSequencenum;
    @XmlElementRef(name = "iam_sequencetime", type = JAXBElement.class, required = false)
    protected JAXBElement<Aodbduration> iamSequencetime;
    @XmlElementRef(name = "iam_severity", type = JAXBElement.class, required = false)
    protected JAXBElement<Aodbstring> iamSeverity;
    @XmlElementRef(name = "iam_sid", type = JAXBElement.class, required = false)
    protected JAXBElement<Aodbstring> iamSid;
    @XmlElementRef(name = "iam_slottime", type = JAXBElement.class, required = false)
    protected JAXBElement<Aodbduration> iamSlottime;
    @XmlElementRef(name = "iam_slot_from", type = JAXBElement.class, required = false)
    protected JAXBElement<Aodbduration> iamSlotFrom;
    @XmlElementRef(name = "iam_slot_to", type = JAXBElement.class, required = false)
    protected JAXBElement<Aodbduration> iamSlotTo;
    @XmlElementRef(name = "iam_ssrcode", type = JAXBElement.class, required = false)
    protected JAXBElement<Aodbstring> iamSsrcode;
    @XmlElementRef(name = "iam_star", type = JAXBElement.class, required = false)
    protected JAXBElement<Aodbstring> iamStar;
    @XmlElementRef(name = "iam_startupgiventime", type = JAXBElement.class, required = false)
    protected JAXBElement<Aodbduration> iamStartupgiventime;
    @XmlElementRef(name = "iam_status", type = JAXBElement.class, required = false)
    protected JAXBElement<Aodbstring> iamStatus;
    @XmlElementRef(name = "iam_taxitime", type = JAXBElement.class, required = false)
    protected JAXBElement<Aodbinteger> iamTaxitime;
    @XmlElementRef(name = "iam_title", type = JAXBElement.class, required = false)
    protected JAXBElement<Aodbstring> iamTitle;
    @XmlElementRef(name = "iam_wktrc", type = JAXBElement.class, required = false)
    protected JAXBElement<Aodbstring> iamWktrc;
    @XmlElementRef(name = "iam_xmlmessage", type = JAXBElement.class, required = false)
    protected JAXBElement<Aodbstring> iamXmlmessage;
    @XmlElementRef(name = "iam_pa_arrival", type = JAXBElement.class, required = false)
    protected JAXBElement<Aodbinteger> iamPaArrival;
    @XmlElementRef(name = "iam_pd_departure", type = JAXBElement.class, required = false)
    protected JAXBElement<Aodbinteger> iamPdDeparture;
    @XmlElementRef(name = "iam_syst_station", type = JAXBElement.class, required = false)
    protected JAXBElement<Aodbstring> iamSystStation;
    @XmlAttribute(name = "action")
    protected ActionType action;
    @XmlAttribute(name = "id")
    protected String id;

    /**
     * Gets the value of the iamAction property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link Aodbstring }{@code >}
     *     
     */
    public JAXBElement<Aodbstring> getIamAction() {
        return iamAction;
    }

    /**
     * Sets the value of the iamAction property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link Aodbstring }{@code >}
     *     
     */
    public void setIamAction(JAXBElement<Aodbstring> value) {
        this.iamAction = value;
    }

    /**
     * Gets the value of the iamAdep property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link Aodbstring }{@code >}
     *     
     */
    public JAXBElement<Aodbstring> getIamAdep() {
        return iamAdep;
    }

    /**
     * Sets the value of the iamAdep property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link Aodbstring }{@code >}
     *     
     */
    public void setIamAdep(JAXBElement<Aodbstring> value) {
        this.iamAdep = value;
    }

    /**
     * Gets the value of the iamAdes property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link Aodbstring }{@code >}
     *     
     */
    public JAXBElement<Aodbstring> getIamAdes() {
        return iamAdes;
    }

    /**
     * Sets the value of the iamAdes property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link Aodbstring }{@code >}
     *     
     */
    public void setIamAdes(JAXBElement<Aodbstring> value) {
        this.iamAdes = value;
    }

    /**
     * Gets the value of the iamAdexpcomment property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link Aodbstring }{@code >}
     *     
     */
    public JAXBElement<Aodbstring> getIamAdexpcomment() {
        return iamAdexpcomment;
    }

    /**
     * Sets the value of the iamAdexpcomment property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link Aodbstring }{@code >}
     *     
     */
    public void setIamAdexpcomment(JAXBElement<Aodbstring> value) {
        this.iamAdexpcomment = value;
    }

    /**
     * Gets the value of the iamArcid property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link Aodbstring }{@code >}
     *     
     */
    public JAXBElement<Aodbstring> getIamArcid() {
        return iamArcid;
    }

    /**
     * Sets the value of the iamArcid property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link Aodbstring }{@code >}
     *     
     */
    public void setIamArcid(JAXBElement<Aodbstring> value) {
        this.iamArcid = value;
    }

    /**
     * Gets the value of the iamArctyp property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link Aodbstring }{@code >}
     *     
     */
    public JAXBElement<Aodbstring> getIamArctyp() {
        return iamArctyp;
    }

    /**
     * Sets the value of the iamArctyp property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link Aodbstring }{@code >}
     *     
     */
    public void setIamArctyp(JAXBElement<Aodbstring> value) {
        this.iamArctyp = value;
    }

    /**
     * Gets the value of the iamArrdepind property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link Aodbstring }{@code >}
     *     
     */
    public JAXBElement<Aodbstring> getIamArrdepind() {
        return iamArrdepind;
    }

    /**
     * Sets the value of the iamArrdepind property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link Aodbstring }{@code >}
     *     
     */
    public void setIamArrdepind(JAXBElement<Aodbstring> value) {
        this.iamArrdepind = value;
    }

    /**
     * Gets the value of the iamAsat property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link Aodbduration }{@code >}
     *     
     */
    public JAXBElement<Aodbduration> getIamAsat() {
        return iamAsat;
    }

    /**
     * Sets the value of the iamAsat property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link Aodbduration }{@code >}
     *     
     */
    public void setIamAsat(JAXBElement<Aodbduration> value) {
        this.iamAsat = value;
    }

    /**
     * Gets the value of the iamAsrt property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link Aodbduration }{@code >}
     *     
     */
    public JAXBElement<Aodbduration> getIamAsrt() {
        return iamAsrt;
    }

    /**
     * Sets the value of the iamAsrt property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link Aodbduration }{@code >}
     *     
     */
    public void setIamAsrt(JAXBElement<Aodbduration> value) {
        this.iamAsrt = value;
    }

    /**
     * Gets the value of the iamAtot property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link Aodbduration }{@code >}
     *     
     */
    public JAXBElement<Aodbduration> getIamAtot() {
        return iamAtot;
    }

    /**
     * Sets the value of the iamAtot property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link Aodbduration }{@code >}
     *     
     */
    public void setIamAtot(JAXBElement<Aodbduration> value) {
        this.iamAtot = value;
    }

    /**
     * Gets the value of the iamCallsign property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link Aodbstring }{@code >}
     *     
     */
    public JAXBElement<Aodbstring> getIamCallsign() {
        return iamCallsign;
    }

    /**
     * Sets the value of the iamCallsign property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link Aodbstring }{@code >}
     *     
     */
    public void setIamCallsign(JAXBElement<Aodbstring> value) {
        this.iamCallsign = value;
    }

    /**
     * Gets the value of the iamChecktime property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link Aodbduration }{@code >}
     *     
     */
    public JAXBElement<Aodbduration> getIamChecktime() {
        return iamChecktime;
    }

    /**
     * Sets the value of the iamChecktime property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link Aodbduration }{@code >}
     *     
     */
    public void setIamChecktime(JAXBElement<Aodbduration> value) {
        this.iamChecktime = value;
    }

    /**
     * Gets the value of the iamCheckuser property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link Aodbstring }{@code >}
     *     
     */
    public JAXBElement<Aodbstring> getIamCheckuser() {
        return iamCheckuser;
    }

    /**
     * Sets the value of the iamCheckuser property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link Aodbstring }{@code >}
     *     
     */
    public void setIamCheckuser(JAXBElement<Aodbstring> value) {
        this.iamCheckuser = value;
    }

    /**
     * Gets the value of the iamCnl property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link Aodbduration }{@code >}
     *     
     */
    public JAXBElement<Aodbduration> getIamCnl() {
        return iamCnl;
    }

    /**
     * Sets the value of the iamCnl property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link Aodbduration }{@code >}
     *     
     */
    public void setIamCnl(JAXBElement<Aodbduration> value) {
        this.iamCnl = value;
    }

    /**
     * Gets the value of the iamComment property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link Aodbstring }{@code >}
     *     
     */
    public JAXBElement<Aodbstring> getIamComment() {
        return iamComment;
    }

    /**
     * Sets the value of the iamComment property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link Aodbstring }{@code >}
     *     
     */
    public void setIamComment(JAXBElement<Aodbstring> value) {
        this.iamComment = value;
    }

    /**
     * Gets the value of the iamCreatetime property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link Aodbduration }{@code >}
     *     
     */
    public JAXBElement<Aodbduration> getIamCreatetime() {
        return iamCreatetime;
    }

    /**
     * Sets the value of the iamCreatetime property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link Aodbduration }{@code >}
     *     
     */
    public void setIamCreatetime(JAXBElement<Aodbduration> value) {
        this.iamCreatetime = value;
    }

    /**
     * Gets the value of the iamEditedmessage property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link Aodbstring }{@code >}
     *     
     */
    public JAXBElement<Aodbstring> getIamEditedmessage() {
        return iamEditedmessage;
    }

    /**
     * Sets the value of the iamEditedmessage property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link Aodbstring }{@code >}
     *     
     */
    public void setIamEditedmessage(JAXBElement<Aodbstring> value) {
        this.iamEditedmessage = value;
    }

    /**
     * Gets the value of the iamEobt property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link Aodbduration }{@code >}
     *     
     */
    public JAXBElement<Aodbduration> getIamEobt() {
        return iamEobt;
    }

    /**
     * Sets the value of the iamEobt property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link Aodbduration }{@code >}
     *     
     */
    public void setIamEobt(JAXBElement<Aodbduration> value) {
        this.iamEobt = value;
    }

    /**
     * Gets the value of the iamErrorcolumn property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link Aodbinteger }{@code >}
     *     
     */
    public JAXBElement<Aodbinteger> getIamErrorcolumn() {
        return iamErrorcolumn;
    }

    /**
     * Sets the value of the iamErrorcolumn property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link Aodbinteger }{@code >}
     *     
     */
    public void setIamErrorcolumn(JAXBElement<Aodbinteger> value) {
        this.iamErrorcolumn = value;
    }

    /**
     * Gets the value of the iamErrorlineno property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link Aodbinteger }{@code >}
     *     
     */
    public JAXBElement<Aodbinteger> getIamErrorlineno() {
        return iamErrorlineno;
    }

    /**
     * Sets the value of the iamErrorlineno property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link Aodbinteger }{@code >}
     *     
     */
    public void setIamErrorlineno(JAXBElement<Aodbinteger> value) {
        this.iamErrorlineno = value;
    }

    /**
     * Gets the value of the iamErrormessage property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link Aodbstring }{@code >}
     *     
     */
    public JAXBElement<Aodbstring> getIamErrormessage() {
        return iamErrormessage;
    }

    /**
     * Sets the value of the iamErrormessage property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link Aodbstring }{@code >}
     *     
     */
    public void setIamErrormessage(JAXBElement<Aodbstring> value) {
        this.iamErrormessage = value;
    }

    /**
     * Gets the value of the iamEtime property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link Aodbduration }{@code >}
     *     
     */
    public JAXBElement<Aodbduration> getIamEtime() {
        return iamEtime;
    }

    /**
     * Sets the value of the iamEtime property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link Aodbduration }{@code >}
     *     
     */
    public void setIamEtime(JAXBElement<Aodbduration> value) {
        this.iamEtime = value;
    }

    /**
     * Gets the value of the iamEtt property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link Aodbduration }{@code >}
     *     
     */
    public JAXBElement<Aodbduration> getIamEtt() {
        return iamEtt;
    }

    /**
     * Sets the value of the iamEtt property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link Aodbduration }{@code >}
     *     
     */
    public void setIamEtt(JAXBElement<Aodbduration> value) {
        this.iamEtt = value;
    }

    /**
     * Gets the value of the iamFiltim property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link Aodbduration }{@code >}
     *     
     */
    public JAXBElement<Aodbduration> getIamFiltim() {
        return iamFiltim;
    }

    /**
     * Sets the value of the iamFiltim property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link Aodbduration }{@code >}
     *     
     */
    public void setIamFiltim(JAXBElement<Aodbduration> value) {
        this.iamFiltim = value;
    }

    /**
     * Gets the value of the iamFltrul property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link Aodbstring }{@code >}
     *     
     */
    public JAXBElement<Aodbstring> getIamFltrul() {
        return iamFltrul;
    }

    /**
     * Sets the value of the iamFltrul property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link Aodbstring }{@code >}
     *     
     */
    public void setIamFltrul(JAXBElement<Aodbstring> value) {
        this.iamFltrul = value;
    }

    /**
     * Gets the value of the iamFltsrc property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link Aodbstring }{@code >}
     *     
     */
    public JAXBElement<Aodbstring> getIamFltsrc() {
        return iamFltsrc;
    }

    /**
     * Sets the value of the iamFltsrc property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link Aodbstring }{@code >}
     *     
     */
    public void setIamFltsrc(JAXBElement<Aodbstring> value) {
        this.iamFltsrc = value;
    }

    /**
     * Gets the value of the iamFlttyp property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link Aodbstring }{@code >}
     *     
     */
    public JAXBElement<Aodbstring> getIamFlttyp() {
        return iamFlttyp;
    }

    /**
     * Sets the value of the iamFlttyp property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link Aodbstring }{@code >}
     *     
     */
    public void setIamFlttyp(JAXBElement<Aodbstring> value) {
        this.iamFlttyp = value;
    }

    /**
     * Gets the value of the iamFplcat property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link Aodbstring }{@code >}
     *     
     */
    public JAXBElement<Aodbstring> getIamFplcat() {
        return iamFplcat;
    }

    /**
     * Sets the value of the iamFplcat property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link Aodbstring }{@code >}
     *     
     */
    public void setIamFplcat(JAXBElement<Aodbstring> value) {
        this.iamFplcat = value;
    }

    /**
     * Gets the value of the iamHovtm property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link Aodbduration }{@code >}
     *     
     */
    public JAXBElement<Aodbduration> getIamHovtm() {
        return iamHovtm;
    }

    /**
     * Sets the value of the iamHovtm property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link Aodbduration }{@code >}
     *     
     */
    public void setIamHovtm(JAXBElement<Aodbduration> value) {
        this.iamHovtm = value;
    }

    /**
     * Gets the value of the iamIdseq property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link Aodbfloat }{@code >}
     *     
     */
    public JAXBElement<Aodbfloat> getIamIdseq() {
        return iamIdseq;
    }

    /**
     * Sets the value of the iamIdseq property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link Aodbfloat }{@code >}
     *     
     */
    public void setIamIdseq(JAXBElement<Aodbfloat> value) {
        this.iamIdseq = value;
    }

    /**
     * Gets the value of the iamIfplid property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link Aodbstring }{@code >}
     *     
     */
    public JAXBElement<Aodbstring> getIamIfplid() {
        return iamIfplid;
    }

    /**
     * Sets the value of the iamIfplid property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link Aodbstring }{@code >}
     *     
     */
    public void setIamIfplid(JAXBElement<Aodbstring> value) {
        this.iamIfplid = value;
    }

    /**
     * Gets the value of the iamIobt property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link Aodbduration }{@code >}
     *     
     */
    public JAXBElement<Aodbduration> getIamIobt() {
        return iamIobt;
    }

    /**
     * Sets the value of the iamIobt property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link Aodbduration }{@code >}
     *     
     */
    public void setIamIobt(JAXBElement<Aodbduration> value) {
        this.iamIobt = value;
    }

    /**
     * Gets the value of the iamLfztypcode5L property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link Aodbstring }{@code >}
     *     
     */
    public JAXBElement<Aodbstring> getIamLfztypcode5L() {
        return iamLfztypcode5L;
    }

    /**
     * Sets the value of the iamLfztypcode5L property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link Aodbstring }{@code >}
     *     
     */
    public void setIamLfztypcode5L(JAXBElement<Aodbstring> value) {
        this.iamLfztypcode5L = value;
    }

    /**
     * Gets the value of the iamMessagetitle property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link Aodbstring }{@code >}
     *     
     */
    public JAXBElement<Aodbstring> getIamMessagetitle() {
        return iamMessagetitle;
    }

    /**
     * Sets the value of the iamMessagetitle property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link Aodbstring }{@code >}
     *     
     */
    public void setIamMessagetitle(JAXBElement<Aodbstring> value) {
        this.iamMessagetitle = value;
    }

    /**
     * Gets the value of the iamModtime property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link Aodbduration }{@code >}
     *     
     */
    public JAXBElement<Aodbduration> getIamModtime() {
        return iamModtime;
    }

    /**
     * Sets the value of the iamModtime property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link Aodbduration }{@code >}
     *     
     */
    public void setIamModtime(JAXBElement<Aodbduration> value) {
        this.iamModtime = value;
    }

    /**
     * Gets the value of the iamModuser property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link Aodbstring }{@code >}
     *     
     */
    public JAXBElement<Aodbstring> getIamModuser() {
        return iamModuser;
    }

    /**
     * Sets the value of the iamModuser property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link Aodbstring }{@code >}
     *     
     */
    public void setIamModuser(JAXBElement<Aodbstring> value) {
        this.iamModuser = value;
    }

    /**
     * Gets the value of the iamOriginalmessage property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link Aodbstring }{@code >}
     *     
     */
    public JAXBElement<Aodbstring> getIamOriginalmessage() {
        return iamOriginalmessage;
    }

    /**
     * Sets the value of the iamOriginalmessage property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link Aodbstring }{@code >}
     *     
     */
    public void setIamOriginalmessage(JAXBElement<Aodbstring> value) {
        this.iamOriginalmessage = value;
    }

    /**
     * Gets the value of the iamPassive property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link Aodbduration }{@code >}
     *     
     */
    public JAXBElement<Aodbduration> getIamPassive() {
        return iamPassive;
    }

    /**
     * Sets the value of the iamPassive property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link Aodbduration }{@code >}
     *     
     */
    public void setIamPassive(JAXBElement<Aodbduration> value) {
        this.iamPassive = value;
    }

    /**
     * Gets the value of the iamReason property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link Aodbstring }{@code >}
     *     
     */
    public JAXBElement<Aodbstring> getIamReason() {
        return iamReason;
    }

    /**
     * Sets the value of the iamReason property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link Aodbstring }{@code >}
     *     
     */
    public void setIamReason(JAXBElement<Aodbstring> value) {
        this.iamReason = value;
    }

    /**
     * Gets the value of the iamRecipient property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link Aodbstring }{@code >}
     *     
     */
    public JAXBElement<Aodbstring> getIamRecipient() {
        return iamRecipient;
    }

    /**
     * Sets the value of the iamRecipient property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link Aodbstring }{@code >}
     *     
     */
    public void setIamRecipient(JAXBElement<Aodbstring> value) {
        this.iamRecipient = value;
    }

    /**
     * Gets the value of the iamRegistration property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link Aodbstring }{@code >}
     *     
     */
    public JAXBElement<Aodbstring> getIamRegistration() {
        return iamRegistration;
    }

    /**
     * Sets the value of the iamRegistration property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link Aodbstring }{@code >}
     *     
     */
    public void setIamRegistration(JAXBElement<Aodbstring> value) {
        this.iamRegistration = value;
    }

    /**
     * Gets the value of the iamRoute property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link Aodbstring }{@code >}
     *     
     */
    public JAXBElement<Aodbstring> getIamRoute() {
        return iamRoute;
    }

    /**
     * Sets the value of the iamRoute property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link Aodbstring }{@code >}
     *     
     */
    public void setIamRoute(JAXBElement<Aodbstring> value) {
        this.iamRoute = value;
    }

    /**
     * Gets the value of the iamRwy1Dir property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link Aodbstring }{@code >}
     *     
     */
    public JAXBElement<Aodbstring> getIamRwy1Dir() {
        return iamRwy1Dir;
    }

    /**
     * Sets the value of the iamRwy1Dir property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link Aodbstring }{@code >}
     *     
     */
    public void setIamRwy1Dir(JAXBElement<Aodbstring> value) {
        this.iamRwy1Dir = value;
    }

    /**
     * Gets the value of the iamRwy2Dir property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link Aodbstring }{@code >}
     *     
     */
    public JAXBElement<Aodbstring> getIamRwy2Dir() {
        return iamRwy2Dir;
    }

    /**
     * Sets the value of the iamRwy2Dir property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link Aodbstring }{@code >}
     *     
     */
    public void setIamRwy2Dir(JAXBElement<Aodbstring> value) {
        this.iamRwy2Dir = value;
    }

    /**
     * Gets the value of the iamRwydep property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link Aodbstring }{@code >}
     *     
     */
    public JAXBElement<Aodbstring> getIamRwydep() {
        return iamRwydep;
    }

    /**
     * Sets the value of the iamRwydep property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link Aodbstring }{@code >}
     *     
     */
    public void setIamRwydep(JAXBElement<Aodbstring> value) {
        this.iamRwydep = value;
    }

    /**
     * Gets the value of the iamSender property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link Aodbstring }{@code >}
     *     
     */
    public JAXBElement<Aodbstring> getIamSender() {
        return iamSender;
    }

    /**
     * Sets the value of the iamSender property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link Aodbstring }{@code >}
     *     
     */
    public void setIamSender(JAXBElement<Aodbstring> value) {
        this.iamSender = value;
    }

    /**
     * Gets the value of the iamSeqnum property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link Aodbstring }{@code >}
     *     
     */
    public JAXBElement<Aodbstring> getIamSeqnum() {
        return iamSeqnum;
    }

    /**
     * Sets the value of the iamSeqnum property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link Aodbstring }{@code >}
     *     
     */
    public void setIamSeqnum(JAXBElement<Aodbstring> value) {
        this.iamSeqnum = value;
    }

    /**
     * Gets the value of the iamSequencenum property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link Aodbinteger }{@code >}
     *     
     */
    public JAXBElement<Aodbinteger> getIamSequencenum() {
        return iamSequencenum;
    }

    /**
     * Sets the value of the iamSequencenum property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link Aodbinteger }{@code >}
     *     
     */
    public void setIamSequencenum(JAXBElement<Aodbinteger> value) {
        this.iamSequencenum = value;
    }

    /**
     * Gets the value of the iamSequencetime property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link Aodbduration }{@code >}
     *     
     */
    public JAXBElement<Aodbduration> getIamSequencetime() {
        return iamSequencetime;
    }

    /**
     * Sets the value of the iamSequencetime property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link Aodbduration }{@code >}
     *     
     */
    public void setIamSequencetime(JAXBElement<Aodbduration> value) {
        this.iamSequencetime = value;
    }

    /**
     * Gets the value of the iamSeverity property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link Aodbstring }{@code >}
     *     
     */
    public JAXBElement<Aodbstring> getIamSeverity() {
        return iamSeverity;
    }

    /**
     * Sets the value of the iamSeverity property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link Aodbstring }{@code >}
     *     
     */
    public void setIamSeverity(JAXBElement<Aodbstring> value) {
        this.iamSeverity = value;
    }

    /**
     * Gets the value of the iamSid property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link Aodbstring }{@code >}
     *     
     */
    public JAXBElement<Aodbstring> getIamSid() {
        return iamSid;
    }

    /**
     * Sets the value of the iamSid property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link Aodbstring }{@code >}
     *     
     */
    public void setIamSid(JAXBElement<Aodbstring> value) {
        this.iamSid = value;
    }

    /**
     * Gets the value of the iamSlottime property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link Aodbduration }{@code >}
     *     
     */
    public JAXBElement<Aodbduration> getIamSlottime() {
        return iamSlottime;
    }

    /**
     * Sets the value of the iamSlottime property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link Aodbduration }{@code >}
     *     
     */
    public void setIamSlottime(JAXBElement<Aodbduration> value) {
        this.iamSlottime = value;
    }

    /**
     * Gets the value of the iamSlotFrom property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link Aodbduration }{@code >}
     *     
     */
    public JAXBElement<Aodbduration> getIamSlotFrom() {
        return iamSlotFrom;
    }

    /**
     * Sets the value of the iamSlotFrom property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link Aodbduration }{@code >}
     *     
     */
    public void setIamSlotFrom(JAXBElement<Aodbduration> value) {
        this.iamSlotFrom = value;
    }

    /**
     * Gets the value of the iamSlotTo property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link Aodbduration }{@code >}
     *     
     */
    public JAXBElement<Aodbduration> getIamSlotTo() {
        return iamSlotTo;
    }

    /**
     * Sets the value of the iamSlotTo property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link Aodbduration }{@code >}
     *     
     */
    public void setIamSlotTo(JAXBElement<Aodbduration> value) {
        this.iamSlotTo = value;
    }

    /**
     * Gets the value of the iamSsrcode property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link Aodbstring }{@code >}
     *     
     */
    public JAXBElement<Aodbstring> getIamSsrcode() {
        return iamSsrcode;
    }

    /**
     * Sets the value of the iamSsrcode property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link Aodbstring }{@code >}
     *     
     */
    public void setIamSsrcode(JAXBElement<Aodbstring> value) {
        this.iamSsrcode = value;
    }

    /**
     * Gets the value of the iamStar property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link Aodbstring }{@code >}
     *     
     */
    public JAXBElement<Aodbstring> getIamStar() {
        return iamStar;
    }

    /**
     * Sets the value of the iamStar property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link Aodbstring }{@code >}
     *     
     */
    public void setIamStar(JAXBElement<Aodbstring> value) {
        this.iamStar = value;
    }

    /**
     * Gets the value of the iamStartupgiventime property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link Aodbduration }{@code >}
     *     
     */
    public JAXBElement<Aodbduration> getIamStartupgiventime() {
        return iamStartupgiventime;
    }

    /**
     * Sets the value of the iamStartupgiventime property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link Aodbduration }{@code >}
     *     
     */
    public void setIamStartupgiventime(JAXBElement<Aodbduration> value) {
        this.iamStartupgiventime = value;
    }

    /**
     * Gets the value of the iamStatus property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link Aodbstring }{@code >}
     *     
     */
    public JAXBElement<Aodbstring> getIamStatus() {
        return iamStatus;
    }

    /**
     * Sets the value of the iamStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link Aodbstring }{@code >}
     *     
     */
    public void setIamStatus(JAXBElement<Aodbstring> value) {
        this.iamStatus = value;
    }

    /**
     * Gets the value of the iamTaxitime property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link Aodbinteger }{@code >}
     *     
     */
    public JAXBElement<Aodbinteger> getIamTaxitime() {
        return iamTaxitime;
    }

    /**
     * Sets the value of the iamTaxitime property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link Aodbinteger }{@code >}
     *     
     */
    public void setIamTaxitime(JAXBElement<Aodbinteger> value) {
        this.iamTaxitime = value;
    }

    /**
     * Gets the value of the iamTitle property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link Aodbstring }{@code >}
     *     
     */
    public JAXBElement<Aodbstring> getIamTitle() {
        return iamTitle;
    }

    /**
     * Sets the value of the iamTitle property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link Aodbstring }{@code >}
     *     
     */
    public void setIamTitle(JAXBElement<Aodbstring> value) {
        this.iamTitle = value;
    }

    /**
     * Gets the value of the iamWktrc property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link Aodbstring }{@code >}
     *     
     */
    public JAXBElement<Aodbstring> getIamWktrc() {
        return iamWktrc;
    }

    /**
     * Sets the value of the iamWktrc property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link Aodbstring }{@code >}
     *     
     */
    public void setIamWktrc(JAXBElement<Aodbstring> value) {
        this.iamWktrc = value;
    }

    /**
     * Gets the value of the iamXmlmessage property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link Aodbstring }{@code >}
     *     
     */
    public JAXBElement<Aodbstring> getIamXmlmessage() {
        return iamXmlmessage;
    }

    /**
     * Sets the value of the iamXmlmessage property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link Aodbstring }{@code >}
     *     
     */
    public void setIamXmlmessage(JAXBElement<Aodbstring> value) {
        this.iamXmlmessage = value;
    }

    /**
     * Gets the value of the iamPaArrival property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link Aodbinteger }{@code >}
     *     
     */
    public JAXBElement<Aodbinteger> getIamPaArrival() {
        return iamPaArrival;
    }

    /**
     * Sets the value of the iamPaArrival property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link Aodbinteger }{@code >}
     *     
     */
    public void setIamPaArrival(JAXBElement<Aodbinteger> value) {
        this.iamPaArrival = value;
    }

    /**
     * Gets the value of the iamPdDeparture property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link Aodbinteger }{@code >}
     *     
     */
    public JAXBElement<Aodbinteger> getIamPdDeparture() {
        return iamPdDeparture;
    }

    /**
     * Sets the value of the iamPdDeparture property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link Aodbinteger }{@code >}
     *     
     */
    public void setIamPdDeparture(JAXBElement<Aodbinteger> value) {
        this.iamPdDeparture = value;
    }

    /**
     * Gets the value of the iamSystStation property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link Aodbstring }{@code >}
     *     
     */
    public JAXBElement<Aodbstring> getIamSystStation() {
        return iamSystStation;
    }

    /**
     * Sets the value of the iamSystStation property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link Aodbstring }{@code >}
     *     
     */
    public void setIamSystStation(JAXBElement<Aodbstring> value) {
        this.iamSystStation = value;
    }

    /**
     * Gets the value of the action property.
     * 
     * @return
     *     possible object is
     *     {@link ActionType }
     *     
     */
    public ActionType getAction() {
        return action;
    }

    /**
     * Sets the value of the action property.
     * 
     * @param value
     *     allowed object is
     *     {@link ActionType }
     *     
     */
    public void setAction(ActionType value) {
        this.action = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

}
