//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.05.19 at 12:07:30 PM ICT 
//


package sf.sfis.miniesb.esb.filereadyout;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for FILEACTION.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="FILEACTION">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;whiteSpace value="preserve"/>
 *     &lt;enumeration value="HANDLEXML"/>
 *     &lt;enumeration value="HANDLEFTP"/>
 *     &lt;enumeration value="FILEREQUEST"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "FILEACTION")
@XmlEnum
public enum FILEACTION {

    HANDLEXML,
    HANDLEFTP,
    FILEREQUEST;

    public String value() {
        return name();
    }

    public static FILEACTION fromValue(String v) {
        return valueOf(v);
    }

}
